id: IssueManagement.LabelUserType
name: GitOps.PullRequestIssueManagement
description: Label issues and PRs based on author permissions (User-Maintainer or User-Community)
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Label issue as User-Maintainer if author has Write or Admin permissions
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - or:
              - activitySenderHasPermission:
                  permission: Write
              - activitySenderHasPermission:
                  permission: Admin
        then:
          - addLabel:
              label: User-Maintainer
      
      - description: Label issue as User-Community if author does not have Write or Admin permissions
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - not:
              or:
                - activitySenderHasPermission:
                    permission: Write
                - activitySenderHasPermission:
                    permission: Admin
        then:
          - addLabel:
              label: User-Community
      
      - description: Label PR as User-Maintainer if author has Write or Admin permissions
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - activitySenderHasPermission:
                  permission: Write
              - activitySenderHasPermission:
                  permission: Admin
        then:
          - addLabel:
              label: User-Maintainer
      
      - description: Label PR as User-Community if author does not have Write or Admin permissions
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - not:
              or:
                - activitySenderHasPermission:
                    permission: Write
                - activitySenderHasPermission:
                    permission: Admin
        then:
          - addLabel:
              label: User-Community
onFailure:
onSuccess:
