#  
# Module manifest for module 'AzureRM.NetCore.Preview'  
#  
# Generated by: Microsoft Corporation  
#  
# Generated on: 9/18/2015  
#  
  
@{  
  
#Base module
RootModule = ''

# Version number of this module.  
ModuleVersion = '0.3.0'  

# Supported PSEditions
CompatiblePSEditions = 'Core'

# ID used to uniquely identify this module  
GUID = 'B433E830-B479-4F7F-9C80-9CC6C28E1B51'  
  
# Author of this module  
Author = 'Microsoft Corporation'  
  
# Company or vendor of this module  
CompanyName = 'Microsoft Corporation'  
  
# Copyright statement for this module  
Copyright = 'Microsoft Corporation. All rights reserved.'    
  
# Description of the functionality provided by this module  
Description = 'Azure Resource Manager Module'  
  
# Minimum version of the Windows PowerShell engine required by this module  
PowerShellVersion = '5.1'  
  
# Name of the Windows PowerShell host required by this module  
# PowerShellHostName = ''  
  
# Minimum version of the Windows PowerShell host required by this module  
# PowerShellHostVersion = ''  
  
# Minimum version of the .NET Framework required by this module  
# DotNetFrameworkVersion = ''  
  
# Minimum version of the common language runtime (CLR) required by this module  
# CLRVersion=''  
  
# Processor architecture (None, X86, Amd64, IA64) required by this module  
ProcessorArchitecture = 'None'  
  
# Modules that must be imported into the global environment prior to importing this module  
RequiredModules = @(
   @{ModuleName="AzureRM.Profile.NetCore.Preview"; RequiredVersion="0.3.0"},
   @{ModuleName="AzureRM.Resources.NetCore.Preview"; RequiredVersion="0.3.0"}
) 
  
# Assemblies that must be loaded prior to importing this module  
RequiredAssemblies = @()  
  
# Script files (.ps1) that are run in the caller's environment prior to importing this module  
ScriptsToProcess = @()  
  
# Type files (.ps1xml) to be loaded when importing this module  
TypesToProcess = @(
)  
  
# Format files (.ps1xml) to be loaded when importing this module  
FormatsToProcess = @( 
)  
  
# Modules to import as nested modules of the module specified in ModuleToProcess  
NestedModules = @()  
  
# Functions to export from this module  
FunctionsToExport = '*'  
  
# Cmdlets to export from this module  
CmdletsToExport = '*'  
  
# Variables to export from this module  
VariablesToExport = '*'  
  
# Aliases to export from this module  
AliasesToExport = '*'  
  
# List of all modules packaged with this module  
ModuleList = @()  
  
# List of all files packaged with this module  
FileList =  @()  
  
# Private data to pass to the module specified in ModuleToProcess  
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @('Azure', 'ResourceManager', 'ARM')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/Azure/azure-powershell/dev/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/Azure/azure-powershell/blob/dev/ChangeLog.md'

    } # End of PSData hashtable

} # End of PrivateData hashtable  

} 
