version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "release/*"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "release/*"
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: "/tools/AttackSurfaceAnalyzer/docker"
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: "/tools/AttackSurfaceAnalyzer/docker"
    target-branch: "release/v7.4"
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: "/tools/AttackSurfaceAnalyzer/docker"
    target-branch: "release/v7.5"
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"

  - package-ecosystem: "docker"
    directory: "/tools/AttackSurfaceAnalyzer/docker"
    target-branch: "release/v7.6"
    schedule:
      interval: daily
    labels:
      - "CL-BuildPackaging"
