//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class EventingResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal EventingResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventingResources", typeof(EventingResources).GetTypeInfo().Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The action is not supported when you are forwarding events..
    /// </summary>
    internal static string ActionAndForwardNotSupported {
        get {
            return ResourceManager.GetString("ActionAndForwardNotSupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot register for the specified event. An event with the name &apos;{0}&apos; does not exist..
    /// </summary>
    internal static string CouldNotFindEvent {
        get {
            return ResourceManager.GetString("CouldNotFindEvent", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot register for the specified event. Events that require a return value are not supported..
    /// </summary>
    internal static string NonVoidDelegateNotSupported {
        get {
            return ResourceManager.GetString("NonVoidDelegateNotSupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This operation is not supported on remote instances..
    /// </summary>
    internal static string RemoteOperationNotSupported {
        get {
            return ResourceManager.GetString("RemoteOperationNotSupported", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot register for the specified event. The event source identifier &apos;{0}&apos; is reserved for the Windows PowerShell engine..
    /// </summary>
    internal static string ReservedIdentifier {
        get {
            return ResourceManager.GetString("ReservedIdentifier", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cannot subscribe to the specified event. A subscriber with the source identifier &apos;{0}&apos; already exists..
    /// </summary>
    internal static string SubscriberExists {
        get {
            return ResourceManager.GetString("SubscriberExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Windows PowerShell cannot subscribe to Windows RT events..
    /// </summary>
    internal static string WinRTEventsNotSupported {
        get {
            return ResourceManager.GetString("WinRTEventsNotSupported", resourceCulture);
        }
    }
}
