parameters:
  pool: 'macOS-latest'
  purpose: ''
  tagSet: 'CI'
  name: 'mac'

jobs:
- job: ${{ parameters.name }}_test_${{ parameters.purpose }}_${{ parameters.tagSet }}

  pool:
    vmImage: ${{ parameters.pool }}

  displayName: ${{ parameters.name }} Test - ${{ parameters.purpose }} - ${{ parameters.tagSet }}

  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        useGlobalJson: true
        packageType: 'sdk'

    - template: ./test/nix-test-steps.yml
      parameters:
        purpose: ${{ parameters.purpose }}
        tagSet: ${{ parameters.tagSet }}
