name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - /tools/install-powershell.sh
    - /tools/installpsh-amazonlinux.sh
    - /tools/installpsh-debian.sh
    - /tools/installpsh-osx.sh
    - /tools/installpsh-redhat.sh
    - /tools/installpsh-suse.sh
    - /tools/install-powershell.ps1
pr:
  branches:
    include:
    - master
    - release*
  paths:
    include:
    - /tools/install-powershell.sh
    - /tools/installpsh-amazonlinux.sh
    - /tools/installpsh-debian.sh
    - /tools/installpsh-osx.sh
    - /tools/installpsh-redhat.sh
    - /tools/installpsh-suse.sh
    - /tools/install-powershell.ps1

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

resources:
- repo: self
  clean: true
phases:
- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellUbuntu
    pool: Hosted Ubuntu 1604

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellUbuntu
    pool: Hosted Ubuntu 1604

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellAmazonLinux
    pool: Hosted Ubuntu 1604
    container: amazonlinux:latest

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellCentOS
    pool: Hosted Ubuntu 1604
    container: centos:7

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellOpenSUSE
    pool: Hosted Ubuntu 1604
    container: opensuse:42.3

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: ./tools/install-powershell.sh
    jobName: InstallPowerShellMacOS
    pool: Hosted macOS

- template: templates/install-ps-phase.yml
  parameters:
    scriptName: pwsh -c ./tools/install-powershell.ps1 -AddToPath
    jobName: InstallPowerShellPS1Ubuntu
    pool: Hosted Ubuntu 1604
