parameters:
  - name: ContainerPattern
    displayName: |
      Pattern to match JobName of the container.
      Update this to force a container.
      `.` will match everything
    type: string
    default: .

name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
    - .vsts-ci/misc-analysis.yml
    - .github/ISSUE_TEMPLATE/*
    - .github/workflows/*
    - .dependabot/config.yml
    - .pipelines/*
    - test/perf/*
pr:
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - .vsts-ci/linux.yml
    - .vsts-ci/linux/templates/packaging.yml
    - assets/manpage/*
    - build.psm1
    - global.json
    - nuget.config
    - PowerShell.Common.props
    - src/*.csproj
    - tools/ci.psm1
    - tools/packaging/*

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none

resources:
  repositories:
    - repository: Docker
      type: github
      endpoint: PowerShell
      name: PowerShell/PowerShell-Docker
      ref: master

stages:
- stage: BuildLinuxStage
  displayName: Build for Linux
  jobs:
  - template: templates/ci-build.yml
    parameters:
      pool: ubuntu-latest
      jobName: linux_build
      displayName: linux Build

- stage: PackageLinux
  displayName: Package Linux
  dependsOn: ["BuildLinuxStage"]
  jobs:
  - template: linux/templates/packaging.yml
    parameters:
      pool: ubuntu-latest
