name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

pr:
  branches:
    include:
    - master
    - release*
  paths:
    exclude:
    - /src/*

resources:
- repo: self
  clean: true
phases:
- phase: Linux_CI

  queue:
    name: Hosted Ubuntu 1604
  steps:
  - powershell: |
      Get-ChildItem -Path env:
    displayName: Capture environment
    condition: succeededOrFailed()
  - bash: |
      sudo npm install -g markdown-spellcheck@0.11.0
    displayName: Install mdspell
    condition: succeededOrFailed()
  - bash: |
      sudo npm install -g markdown-link-check@3.7.2
    # WARNING: Keep markdown-link-check pinned at 3.7.2 OR ELSE...
    displayName: Install markdown-link-check
    condition: succeededOrFailed()
  - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhmmss"))"
    displayName: Set Build Name for Non-PR
    condition: ne(variables['Build.Reason'], 'PullRequest')
  - bash: |
      mdspell '**/*.md' '!**/Pester/**/*.md' --ignore-numbers --ignore-acronyms --report --en-us;
    displayName: Test Spelling
    condition: succeededOrFailed()
  - powershell: |
      Import-module ./build.psm1
      $path = './linkResults.xml'
      $path = (Resolve-Path -path $path).ProviderPath
      $results = invoke-pester -Script ./test/common -OutputFile $path -OutputFormat NUnitXml -PassThru
      Write-Host "##vso[results.publish type=NUnit;mergeResults=true;runTitle=Test Markdown Links;publishRunAttachments=true;resultFiles=$path;]"
      if($results.TotalCount -eq 0 -or $results.FailedCount -gt 0)
      {
        throw "markdown link tests failed"
      }
    displayName: Test Links
    condition: succeededOrFailed()
