name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
trigger:
  # Batch merge builds together while a merge build is running
  batch: true
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
    - /.vsts-ci/misc-analysis.yml
    - /.github/ISSUE_TEMPLATE/*
    - /.dependabot/config.yml
pr:
  branches:
    include:
    - master
    - release*
    - feature*
  paths:
    include:
    - '*'
    exclude:
<<<<<<< HEAD
<<<<<<< HEAD
    - .vsts-ci/misc-analysis.yml
    - .github/ISSUE_TEMPLATE/*
    - .dependabot/config.yml
    - tools/releaseBuild/*
    - tools/releaseBuild/azureDevOps/templates/*
    - test/common/markdown/*
=======
    - /.vsts-ci/misc-analysis.yml
    - /.github/ISSUE_TEMPLATE/*
    - /.dependabot/config.yml
    - tools/releaseBuild/*
    - tools/releaseBuild/azureDevOps/templates/*
>>>>>>> upstream/release/v7.0.4
=======
    - .vsts-ci/misc-analysis.yml
    - .github/ISSUE_TEMPLATE/*
    - .dependabot/config.yml
    - tools/releaseBuild/*
    - tools/releaseBuild/azureDevOps/templates/*
    - test/common/markdown/*
>>>>>>> origin/release/v7.1.1

variables:
  GIT_CONFIG_PARAMETERS: "'core.autocrlf=false'"
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: https://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  __SuppressAnsiEscapeSequences: 1

resources:
- repo: self
  clean: true

stages:
- stage: BuildWin
  displayName: Build for Windows
  jobs:
  - template: templates/ci-build.yml

- stage: TestWin
  displayName: Test for Windows
  jobs:
  - template: templates/windows-test.yml
    parameters:
      purpose: UnelevatedPesterTests
      tagSet: CI

  - template: templates/windows-test.yml
    parameters:
      purpose: ElevatedPesterTests
      tagSet: CI

  - template: templates/windows-test.yml
    parameters:
      purpose: UnelevatedPesterTests
      tagSet: Others

  - template: templates/windows-test.yml
    parameters:
      purpose: ElevatedPesterTests
      tagSet: Others

  - template: templates/verify-xunit.yml
<<<<<<< HEAD
=======

- stage: PackagingWin
  displayName: Packaging for Windows
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it
  jobs:
  # Unlike daily builds, we do not upload nuget package to MyGet so we do not wait on tests to finish.
  - template: templates/windows-packaging.yml

>>>>>>> upstream/release/v7.0.4
