name: Compliance-$(Build.BuildId)

trigger: none
pr: none

schedules:
  # Chrontab format, see https://en.wikipedia.org/wiki/Cron
  # this is in UTC
  - cron: '0 13 * * *'
    branches:
      include:
      - master

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance
    ref: master

parameters:
- name: InternalSDKBlobURL
  displayName: URL to the blob havibg internal .NET SDK
  type: string

variables:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1
  - name: POWERSHELL_TELEMETRY_OPTOUT
    value: 1
  - name: nugetMultiFeedWarnLevel
    value: none
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  # Defines the variables AzureFileCopySubscription, StorageAccount, StorageAccountKey, StorageResourceGroup, StorageSubscriptionName
  - group: 'Azure Blob variable group'
  # Defines the variables CgPat, CgOrganization, and CgProject
  - group: 'ComponentGovernance'
  - group: 'PoolNames'
  - name: __DOTNET_RUNTIME_FEED
    value: ${{ parameters.InternalSDKBlobURL }}


stages:
  - stage: compliance
    displayName: 'Compliance'
    dependsOn: []
    jobs:
      - template: templates/compliance/compliance.yml
        parameters:
          parentJobs: []
  - stage: APIScan
    displayName: 'ApiScan'
    dependsOn: []
    jobs:
      - template: templates/compliance/apiscan.yml
        parameters:
          parentJobs: []
  - stage: notice
    displayName: Generate Notice File
    dependsOn: []
    jobs:
      - template: templates/compliance/generateNotice.yml
        parameters:
          parentJobs: []
