@startuml

' Define the build tasks as business processes
agent "Build DEB"  as BuildDEB
agent "Build RPM"  as BuildRPM
agent "Build Alpine"  as BuildAlpine
agent "Build Linux-FxDependent"  as BuildLinuxFx

artifact "Upload DEB"  as UploadDEB
artifact "Upload RPM"  as UploadRPM
artifact "Upload Alpine"  as UploadAlpine
artifact "Upload Linux-FxDependent"  as UploadLinuxFx

agent "Build macOS"  as BuildMac
agent "macOS Package Signing and Upload"  as SignMac

agent "Build Windows - x64"  as BuildWinX64
agent "Build Windows - x86"  as BuildWinX86
agent "Build Windows - arm32"  as BuildWinArm32
agent "Build Windows - arm64"  as BuildWinArm64
agent "Build Windows - FxDependent"  as BuildWinFx
agent "Windows Package Signing and Upload"  as SignWin

agent "ComponentRegistration"  as BuildCG

agent "Compliance"  as Compliance

agent "Create & Upload FxDependent SDK - Linux" as BuildLinuxFxSdk
agent "Create & Upload FxDependent SDK - Windows" as BuildWinFxSdk

' Define finishing the build as a goal filled
control "Finish"  as Finish
control "Start" as Start

' map the various Upload task dependencies
BuildDEB -down-> UploadDEB
BuildRPM -down-> UploadRPM
BuildLinuxFx -down-> UploadLinuxFx
BuildAlpine -down-> UploadAlpine

' map all of the SignMac task dependencies
BuildMac -down-> SignMac

' map all of the SignWin task dependencies
BuildWinX64 -down-> SignWin
BuildWinX86 -down-> SignWin
BuildWinArm32 -down-> SignWin
BuildWinArm64 -down-> SignWin
BuildWinFx -down-> SignWin

' map all of the Compliance task dependencies
BuildWinX86 -down-> Compliance
BuildWinX64 -down-> Compliance
BuildWinFx -down-> Compliance

BuildLinuxFx -down-> BuildLinuxFxSdk
SignWin -down-> BuildWinFxSdk

' map all leafs to finish
Compliance ~~ Finish
UploadAlpine ~~ Finish
UploadDEB ~~ Finish
UploadRPM ~~ Finish
UploadLinuxFx ~~ Finish
SignMac ~~ Finish
BuildCG ~~ Finish
BuildLinuxFxSdk ~~ Finish
BuildWinFxSdk ~~ Finish

Start ~~ BuildDEB
Start ~~ BuildRPM
Start ~~ BuildAlpine
Start ~~ BuildLinuxFx
Start ~~ BuildMac
Start ~~ BuildWinX64
Start ~~ BuildWinX86
Start ~~ BuildWinFx
Start ~~ BuildWinArm32
Start ~~ BuildWinArm64

@enduml
