name: UnifiedPackageBuild-$(Build.BuildId)
trigger:
  branches:
    include:
    - master
    - release*
pr:
  branches:
    include:
    - master
    - release*

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

# Set AzDevOps Agent to clean the machine after the end of the build
resources:
- repo: self
  clean: true

jobs:
- template: templates/linux.yml
  parameters:
    buildName: deb

- template: templates/linux.yml
  parameters:
    buildName: rpm

- template: templates/linux.yml
  parameters:
    buildName: fxdependent

- template: templates/linux.yml
  parameters:
    buildName: alpine

- template: templates/dotnetsdk-fxdependent.yml
  parameters:
    parentJobs:
      - build_fxdependent
    poolName: Hosted Ubuntu 1604
    buildName: Linux

- template: templates/mac.yml

- template: templates/windows-build.yml
  parameters:
    Architecture: x64

- template: templates/windows-build.yml
  parameters:
    Architecture: x86

- template: templates/windows-build.yml
  parameters:
    Architecture: arm

- template: templates/windows-build.yml
  parameters:
    Architecture: arm64

- template: templates/windows-build.yml
  parameters:
    Architecture: fxdependent

- template: templates/dotnetsdk-fxdependent.yml
  parameters:
    parentJobs:
      - WinPackageSigningJob
    poolName: Package ES CodeHub Lab E
    buildName: Windows

- template: templates/windows-component-governance.yml

- template: templates/windows-package-signing.yml
  parameters:
    parentJobs:
      - build_windows_x64
      - build_windows_x86
      - build_windows_arm
      - build_windows_arm64
      - build_windows_fxdependent

- template: templates/mac-package-signing.yml

