name: Working Group Member Request
description: Request membership to serve on a PowerShell Working Group
title: Working Group Member Request
labels: [WG-NeedsReview, WG-Cmdlets, WG-Engine, WG-Interactive-Console, WG-Remoting, Needs-Triage]
body:
- type: markdown
  attributes:
    value: |
      ## Thank you for your interest in joining a PowerShell Working Group. 

      ### Please complete the following public form to request membership to a PowerShell Working Group. 
      
      > [!NOTE]
      > Not all Working Groups are accepting new members at this time.
- type : dropdown
  id : request_type
  validations:
    required: true
  attributes:
    label: Name of Working Group you are requesting to join? 
    description: >-
      Please select the name of the working group you are requesting to join. (Select one)
    options:
      - "Cmdlets and Modules"
      - "Engine"
      - "Interactive UX"
      - "Remoting"
- type: dropdown  
  id: time
  validations:
    required: true
  attributes:
    label: Can you provide at least 1 hour per week to the Working Group? Note that time commitments will vary per Working Group and decided by its members.
    description: >-
      Please select Yes or No.     
    options:
      - "Yes"
      - "No"
- type: markdown  
  attributes:
    value: |
      ## ⚠️ This form is public. Do not provide any private or proprietary information. ⚠️   
- type: textarea
  attributes:
    label: Why do you want to join this working group?
    description: Please provide a brief description of why you want to join this working group.
    placeholder: >
      I want to join this working group because...
  validations:
    required: true
- type: textarea
  attributes:
    label: What skills do you bring to this working group?
    description: Please provide a brief description of what skills you bring to this working group.
    placeholder: >
      I bring the following skills to this working group...
  validations:
    required: true
- type: textarea
  attributes:
    label: Public links to articles, code, or other resources that demonstrate your skills.
    description: Please provide public links to articles, code, or other resources that demonstrate your skills.
    placeholder: >
      I have the following public links to articles, code, or other resources that demonstrate my skills...
  validations:
    required: true

