/* I am really new */
[ClassVersion("1.0.0"), FriendlyName("nxService")]
class MSFT_nxServiceResource : OMI_BaseResource
{
        [key] string Name;
        [write,required,ValueMap{"init", "upstart", "systemd", "*"},Values{"init","upstart","systemd", "*"}] string Controller;
        [write] boolean Enabled;
        [write,ValueMap{"Running", "Stopped"},Values{"Running", "Stopped"}] string State;
        [read] string Path;
        [read] string Description;
        [read] string Runlevels;
};
