parameters:
  buildName: ''
  uploadDisplayName: 'Upload'
  parentJob: ''

jobs:
- job: build_${{ parameters.buildName }}
  displayName: Build ${{ parameters.buildName }}
  condition: succeeded()
  pool:
    name: PowerShell1ES
    demands:
    - ImageOverride -equals PSMMSUbuntu20.04-Secure
  dependsOn: ${{ parameters.parentJob }}
  variables:
    - name: runCodesignValidationInjection
      value: false
    - name: build
      value: ${{ parameters.buildName }}
    - name: NugetSecurityAnalysisWarningLevel
      value: none
    - group: ESRP

  steps:
  - checkout: self
    clean: true

  - checkout: ComplianceRepo
    clean: true

  - template: SetVersionVariables.yml
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)

  - pwsh: |
      # create folder
      sudo mkdir /PowerShell

      # make the current user the owner
      sudo chown $env:USER /PowerShell
    displayName: 'Create /PowerShell'

  - template: cloneToOfficialPath.yml

  - template: insert-nuget-config-azfeed.yml
    parameters:
      repoRoot: $(PowerShellRoot)

  - powershell: |
      import-module "$env:POWERSHELLROOT/build.psm1"
      Sync-PSTags -AddRemoteIfMissing
    displayName: SyncTags
    condition: and(succeeded(), ne(variables['SkipBuild'], 'true'))
    workingDirectory: $(PowerShellRoot)

  - powershell: |
      Import-Module "$env:POWERSHELLROOT/build.psm1"

      Start-PSBootstrap -Package
    displayName: 'Bootstrap'
    condition: and(succeeded(), ne(variables['SkipBuild'], 'true'))
    workingDirectory: $(PowerShellRoot)

  - pwsh: |
      try {
        Import-Module "$env:POWERSHELLROOT/build.psm1"
        Import-Module "$env:POWERSHELLROOT/tools/packaging"

        Invoke-AzDevOpsLinuxPackageBuild -ReleaseTag '$(ReleaseTagVar)' -BuildType '$(build)'
      } catch {
        Get-Error
        throw
      }
    displayName: 'Build'
    condition: and(succeeded(), ne(variables['SkipBuild'], 'true'))
    workingDirectory: $(PowerShellRoot)

  - template: Sbom.yml@ComplianceRepo
    parameters:
      BuildDropPath: '$(System.ArtifactsDirectory)/pwshLinuxBuild'
      Build_Repository_Uri: $(Github_Build_Repository_Uri)
      displayName: ${{ parameters.buildName }} SBOM
      PackageName: PowerShell Linux
      PackageVersion: $(Version)
      sourceScanPath: '$(PowerShellRoot)/tools'

  - ${{ if eq(variables.build,'rpm') }} :
    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: '$(System.ArtifactsDirectory)/pwshMarinerBuildAmd64'
        Build_Repository_Uri: $(Github_Build_Repository_Uri)
        displayName: Mariner SBOM
        PackageName: PowerShell Linux Framework Dependent
        PackageVersion: $(Version)
        sourceScanPath: '$(PowerShellRoot)/tools'

  - ${{ if eq(variables.build,'deb') }} :
    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: '$(System.ArtifactsDirectory)/pwshLinuxBuildMinSize'
        Build_Repository_Uri: $(Github_Build_Repository_Uri)
        displayName: MinSize SBOM
        PackageName: PowerShell Linux Minimum Size
        PackageVersion: $(Version)
        sourceScanPath: '$(PowerShellRoot)/tools'

  - ${{ if eq(variables.build,'deb') }} :
    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm32'
        Build_Repository_Uri: $(Github_Build_Repository_Uri)
        displayName: Arm32 SBOM
        PackageName: PowerShell Linux Arm32
        PackageVersion: $(Version)
        sourceScanPath: '$(PowerShellRoot)/tools'

  - ${{ if eq(variables.build,'deb') }} :
    - template: Sbom.yml@ComplianceRepo
      parameters:
        BuildDropPath: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm64'
        Build_Repository_Uri: $(Github_Build_Repository_Uri)
        displayName: Arm64 SBOM
        PackageName: PowerShell Linux Arm64
        PackageVersion: $(Version)
        sourceScanPath: '$(PowerShellRoot)/tools'

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild'
        artifactName: pwshLinuxBuild

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild-meta'
        artifactName: pwshLinuxBuild-meta

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildMinSize'
        artifactName: pwshLinuxBuildMinSize

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildMinSize-meta'
        artifactName: pwshLinuxBuildMinSize-meta

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm32'
        artifactName: pwshLinuxBuildArm32

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm32-meta'
        artifactName: pwshLinuxBuildArm32-meta

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm64'
        artifactName: pwshLinuxBuildArm64

  - ${{ if eq(variables.build,'deb') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuildArm64-meta'
        artifactName: pwshLinuxBuildArm64-meta

  - ${{ if eq(variables.build,'rpm') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshMarinerBuildAmd64'
        artifactName: pwshMarinerBuildAmd64

  - ${{ if eq(variables.build,'rpm') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshMarinerBuildAmd64-meta'
        artifactName: pwshMarinerBuildAmd64-meta

  - ${{ if eq(variables.build,'alpine') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild'
        artifactName: pwshLinuxBuildAlpine

  - ${{ if eq(variables.build,'alpine') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild-meta'
        artifactName: pwshLinuxBuildAlpine-meta

  - ${{ if eq(variables.build,'fxdependent') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild'
        artifactName: pwshLinuxBuildFxdependent

  - ${{ if eq(variables.build,'fxdependent') }} :
    - task: PublishPipelineArtifact@1
      inputs:
        path: '$(System.ArtifactsDirectory)/pwshLinuxBuild-meta'
        artifactName: pwshLinuxBuildFxdependent-meta
