parameters:
  buildArchitecture: 'x64'

jobs:
- job: build_macOS_${{ parameters.buildArchitecture }}
  displayName: Build macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  pool: Hosted Mac Internal
  variables:
    # Turn off Homebrew analytics
    - name: HOMEBREW_NO_ANALYTICS
      value: 1
    - name: runCodesignValidationInjection
      value: false
    - name: NugetSecurityAnalysisWarningLevel
      value: none
  steps:
  #- task: <task type name>@<version>
  #  inputs:
  #    <task specific inputs>
  #  displayName: '<display name of task>'
  - checkout: self
    clean: true
  - template: SetVersionVariables.yml
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)

  - pwsh: |
      # create folder
      sudo mkdir /PowerShell

      # make the current user the owner
      sudo chown $env:USER /PowerShell
    displayName: 'Create /PowerShell'

  - template: cloneToOfficialPath.yml

  - pwsh: |
      tools/releaseBuild/macOS/PowerShellPackageVsts.ps1 -location $(PowerShellRoot) -BootStrap
    displayName: 'Bootstrap VM'

  - template: /tools/releaseBuild/azureDevOps/templates/insert-nuget-config-azfeed.yml
    parameters:
      repoRoot: $(PowerShellRoot)

  - pwsh: |
      $env:AzDevOpsFeedPAT2 = '$(AzDevOpsFeedPAT2)'
      $(Build.SourcesDirectory)/tools/releaseBuild/macOS/PowerShellPackageVsts.ps1 -ReleaseTag $(ReleaseTagVar) -Destination $(System.ArtifactsDirectory) -Symbols -location $(PowerShellRoot) -Build -ArtifactName macosBinResults -Runtime 'osx-${{ parameters.buildArchitecture }}'
      $env:AzDevOpsFeedPAT2 = $null
    displayName: 'Build'

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
    inputs:
      sourceScanPath: '$(Build.SourcesDirectory)'
      snapshotForceEnabled: true
