parameters:
  - name: depth
    type: number
    default: 1

jobs:
- job: upload_to_artifacts
  displayName: Upload packages
  condition: succeeded()
  pool:
    type: windows
  variables:
  - name: ob_sdl_sbom_enabled
    value: false
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
  - name: ob_sdl_credscan_suppressionsFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
  - name: ob_sdl_codeql_compiled_enabled
    value: false

  steps:
    - checkout: self
      clean: true
      fetchDepth: ${{ parameters.depth }}
      env:
        ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase
      displayName: 'Checkout source code'
    
    - pwsh: |
        git clone --depth ${{ parameters.depth }} https://$(mscodehubCodeReadPat)@mscodehub.visualstudio.com/PowerShellCore/_git/Internal-PowerShellTeam-Tools '$(Pipeline.Workspace)/tools'
      displayName: 'Clone tools repository'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/tools/*'
        artifact: 'tools'
        publishLocation: 'pipeline'
      displayName: 'Publish tools artifact'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/PowerShell/CHANGELOG/*'
        artifact: 'changelog'
        publishLocation: 'pipeline'
      displayName: 'Publish PowerShell artifact'
