parameters:
  - name: skipPublish
    default: false
    type: boolean

jobs:
- job: BuildInfoPublish
  displayName: Publish BuildInfo
  condition: succeeded()
  pool:
    name: PowerShell1ES
    type: windows
    isCustom: true
    demands:
    - ImageOverride -equals PSMMS2019-Secure
  variables:
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - group: 'Azure Blob variable group'
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
  - name: ob_sdl_credscan_suppressionsFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

  - template: release-SetReleaseTagandContainerName.yml

  - pwsh: |
      Get-ChildItem Env:
    displayName: 'Capture Environment Variables'

  - download: PSPackagesOfficial
    artifact: BuildInfoJson
    displayName: Download build info artifact

  - pwsh: |
      $toolsDirectory = '$(Build.SourcesDirectory)/tools'
      Import-Module "$toolsDirectory/ci.psm1"
      $jsonFile = Get-Item "$ENV:PIPELINE_WORKSPACE/PSPackagesOfficial/BuildInfoJson/*.json"
      $fileName = Split-Path $jsonFile -Leaf

      $dateTime = [datetime]::UtcNow
      $dateTime = [datetime]::new($dateTime.Ticks - ($dateTime.Ticks % [timespan]::TicksPerSecond), $dateTime.Kind)

      $metadata = Get-Content -LiteralPath "$toolsDirectory/metadata.json" -ErrorAction Stop | ConvertFrom-Json
      $stableReleaseTag = $metadata.StableReleaseTag -Replace 'v',''

      Write-Verbose -Verbose "Writing $jsonFile contents:"
      $buildInfoJsonContent = Get-Content $jsonFile -Encoding UTF8NoBom -Raw
      Write-Verbose -Verbose $buildInfoJsonContent

      $buildInfo =  $buildInfoJsonContent | ConvertFrom-Json
      $buildInfo.ReleaseDate = $dateTime
      $currentReleaseTag = $buildInfo.ReleaseTag -Replace 'v',''

      $targetFile = "$ENV:PIPELINE_WORKSPACE/$fileName"
      ConvertTo-Json -InputObject $buildInfo | Out-File $targetFile -Encoding ascii

      if ($fileName -eq "preview.json") {
        Set-BuildVariable -Name UploadPreview -Value YES
      } else {
        Set-BuildVariable -Name UploadPreview -Value NO
      }

      Set-BuildVariable -Name PreviewBuildInfoFile -Value $targetFile

      ## Create 'lts.json' if marked as a LTS release.
      if ($fileName -eq "stable.json") {
        [System.Management.Automation.SemanticVersion] $stableVersion = $stableReleaseTag
        [System.Management.Automation.SemanticVersion] $currentVersion = $currentReleaseTag
        if ($ltsRelease) {
          $ltsFile = "$ENV:PIPELINE_WORKSPACE/lts.json"
          Copy-Item -Path $targetFile -Destination $ltsFile -Force
          Set-BuildVariable -Name LTSBuildInfoFile -Value $ltsFile
          Set-BuildVariable -Name UploadLTS -Value YES
        } else {
          Set-BuildVariable -Name UploadLTS -Value NO
        }

        ## Only update the stable.json if the current version is greater than the stable version.
        if ($currentVersion -gt $stableVersion) {
          $versionFile = "$ENV:PIPELINE_WORKSPACE/$($currentVersion.Major)-$($currentVersion.Minor).json"
          Copy-Item -Path $targetFile -Destination $versionFile -Force
          Set-BuildVariable -Name StableBuildInfoFile -Value $versionFile
          Set-BuildVariable -Name UploadStable -Value YES
        } else {
          Set-BuildVariable -Name UploadStable -Value NO
        }

      } else {
        Set-BuildVariable -Name UploadStable -Value NO
      }
    displayName: Create json files

  - task: AzurePowerShell@5
    displayName: Upload buildjson to blob
    inputs:
      azureSubscription: az-blob-cicd-infra
      scriptType: inlineScript
      azurePowerShellVersion: LatestVersion
      pwsh: true
      inline: |
        $containerName = '$web'
        $storageAccount = '$(PSInfraStorageAccount)'
        $prefix = "buildinfo"

        $storageContext = New-AzStorageContext -StorageAccountName $storageAccount -UseConnectedAccount

        #preview
        if ($env:UploadPreview -eq 'YES') {
          $jsonFile = "$env:PreviewBuildInfoFile"
          $blobName = Get-Item $jsonFile | Split-Path -Leaf
          Write-Verbose -Verbose "Uploading $jsonFile to $containerName/$prefix/$blobName"
          Set-AzStorageBlobContent -File $jsonFile -Container $containerName -Blob "$prefix/$blobName" -Context $storageContext -Force
        }

        #LTS
        if ($env:UploadLTS -eq 'YES') {
          $jsonFile = "$env:LTSBuildInfoFile"
          $blobName = Get-Item $jsonFile | Split-Path -Leaf
          Write-Verbose -Verbose "Uploading $jsonFile to $containerName/$prefix/$blobName"
          Set-AzStorageBlobContent -File $jsonFile -Container $containerName -Blob "$prefix/$blobName" -Context $storageContext -Force
        }

        #stable
        if ($env:UploadStable -eq 'YES') {
          $jsonFile = "$env:StableBuildInfoFile"
          $blobName = Get-Item $jsonFile | Split-Path -Leaf
          Write-Verbose -Verbose "Uploading $jsonFile to $containerName/$prefix/$blobName"
          Set-AzStorageBlobContent -File $jsonFile -Container $containerName -Blob "$prefix/$blobName" -Context $storageContext -Force
        }
    condition: and(succeeded(), or(eq(variables['UploadPreview'], 'YES'), eq(variables['UploadLTS'], 'YES'), eq(variables['UploadStable'], 'YES')))