jobs:
- template: /.pipelines/templates/approvalJob.yml@self
  parameters:
    displayName: Approve Blob Public
    jobName: ApproveBlobPublic
    instructions: |
      Are you sure you want to make the blob public?

- job: blobPublic
  displayName: Make Azure Blob Public
  dependsOn: ApproveBlobPublic
  condition: succeeded()
  pool:
    type: windows
  variables:
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - group: 'Azure Blob variable group'
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
  - name: ob_sdl_credscan_suppressionsFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - name: ob_sdl_codeql_compiled_enabled
      value: true

  steps:
  - checkout: self
    clean: true
    env:
      ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

  - template: /.pipelines/templates/SetVersionVariables.yml@self
    parameters:
      ReleaseTagVar: $(ReleaseTagVar)
      CreateJson: yes
      UseJson: no

  - template: /.pipelines/templates/cloneToOfficialPath.yml@self

  - pwsh: |
      Get-ChildItem Env:
    displayName: 'Capture Environment Variables'

  - pwsh: |
      $azureRmModule = Get-InstalledModule AzureRM -ErrorAction SilentlyContinue -Verbose
      if ($azureRmModule) {
        Write-Host 'AzureRM module exists. Removing it'
        Uninstall-AzureRm
        Write-Host 'AzureRM module removed'
      }

      Install-Module -Name Az.Storage -Force -AllowClobber -Scope CurrentUser -Verbose
    displayName: Remove AzRM modules

  - task: AzurePowerShell@5
    displayName: Set blob permissions
    inputs:
      azureSubscription: az-blob-cicd-infra
      scriptType: inlineScript
      azurePowerShellVersion: LatestVersion
      pwsh: true
      inline: |
        $storageAccount = "$(StorageAccount)"
        $containerName = "$(azureVersion)"
        $publicAccess = "blob"

        Set-AzStorageContainerAcl `
          -Context (New-AzStorageContext -StorageAccountName $storageAccount) `
          -Container $containerName `
          -PublicAccess $publicAccess

        Set-AzStorageContainerAcl `
          -Context (New-AzStorageContext -StorageAccountName $storageAccount) `
          -Container "$containerName-gc" `
          -PublicAccess $publicAccess

- template: /.pipelines/templates/approvalJob.yml@self
  parameters:
    displayName: Copy Global tool packages to PSInfra storage
    jobName: CopyBlobApproval
    dependsOnJob: blobPublic
    instructions: |
      Approval for Copy global tool packages to PSInfra storage

- job: PSInfraBlobPublic
  displayName: Copy global tools to PSInfra storage
  dependsOn: CopyBlobApproval
  pool:
    type: windows

  variables:
  - group: 'PSInfraStorage'
  - group: 'Azure Blob variable group'
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'

  steps:
    - checkout: self
      clean: true
      env:
        ob_restore_phase: true # This ensures checkout is done at the beginning of the restore phase

    - template: /.pipelines/templates/SetVersionVariables.yml@self
      parameters:
        ReleaseTagVar: $(ReleaseTagVar)
        CreateJson: yes
        UseJson: no

    - template: /.pipelines/templates/cloneToOfficialPath.yml@self

    - pwsh: |
        Get-ChildItem Env:
      displayName: 'Capture Environment Variables'

    - pwsh: |
        $azureRmModule = Get-InstalledModule AzureRM -ErrorAction SilentlyContinue -Verbose
        if ($azureRmModule) {
          Write-Host 'AzureRM module exists. Removing it'
          Uninstall-AzureRm
          Write-Host 'AzureRM module removed'
        }

        Install-Module -Name Az.Storage -Force -AllowClobber -Scope CurrentUser -Verbose
      displayName: Remove AzRM modules

    - task: AzurePowerShell@5
      displayName: Copy blobs to PSInfra storage
      inputs:
        azureSubscription: az-blob-cicd-infra
        scriptType: inlineScript
        azurePowerShellVersion: LatestVersion
        pwsh: true
        inline: |
          $sourceStorageAccountName = '$(StorageAccount)'
          $sourceContainerName = '$(AzureVersion)'

          $destinationStorageAccountName = '$(PSInfraStorageAccount)'
          $destinationContainerName = "tool/$(Version)"

          $sourceContext = New-AzStorageContext -StorageAccountName $sourceStorageAccountName
          $destinationContext = New-AzStorageContext -StorageAccountName $destinationStorageAccountName

          $blobs = Get-AzStorageBlob -Context $sourceContext -Container $sourceContainerName

          foreach ($blob in $blobs) {
            $sourceBlobName = $blob.Name
            $destinationBlobName = $sourceBlobName

            $destinationBlob = Start-AzStorageBlobCopy -Context $destinationContext -SrcContainer $sourceContainerName -SrcBlob $sourceBlobName -DestContainer $destinationContainerName -DestBlob $destinationBlobName

            # Wait for the copy operation to complete
            $destinationBlob | Wait-AzStorageBlobCopy

            if ($destinationBlob.CopyStatus -eq "Success") {
              Write-Host "Blob copy completed successfully for $sourceBlobName."
            } else {
              Write-Host "Blob copy failed for $sourceBlobName."
            }
          }
