parameters:
  - name: depth
    type: number
    default: 1

jobs:
- job: upload_to_artifacts
  displayName: Upload packages
  condition: succeeded()
  pool:
    type: windows
  variables:
  - group: 'mscodehub-code-read-akv'
  - name: ob_sdl_sbom_enabled
    value: false
  - name: runCodesignValidationInjection
    value: false
  - name: NugetSecurityAnalysisWarningLevel
    value: none
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 1
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: ob_sdl_codeSignValidation_enabled
    value: false
  - name: ob_sdl_binskim_enabled
    value: false
  - name: ob_sdl_tsa_configFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\tsaoptions.json
  - name: ob_sdl_credscan_suppressionsFile
    value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
  - name: ob_sdl_codeSignValidation_enabled
    value: false

  steps:
    - pwsh: |
        git clone --depth ${{ parameters.depth }} https://$(mscodehubCodeReadPat)@mscodehub.visualstudio.com/PowerShellCore/_git/Internal-PowerShellTeam-Tools '$(Pipeline.Workspace)/tools'
      displayName: 'Clone tools repository'
    
    - pwsh: |
        New-Item -ItemType Directory -Path "$(ob_outputDirectory)/tools"
        Copy-Item "$(Pipeline.Workspace)/tools/*" -Destination "$(ob_outputDirectory)/tools" -Recurse -Force -Verbose
      displayName: 'Upload tools to artifacts'

    - pwsh: |
        New-Item -ItemType Directory -Path "$(ob_outputDirectory)/CHANGELOG"
        Copy-Item "$(REPOROOT)/CHANGELOG/*" -Destination "$(ob_outputDirectory)/CHANGELOG" -Force -Verbose
      displayName: 'Upload changelog to artifacts'
