jobs:
- job: CopyEV2FilesToArtifact
  displayName: Copy EV2 Files to Artifact
  pool:
    type: windows
  variables:
  - name: ob_outputDirectory
    value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
  - name: repoRoot
    value: '$(Build.SourcesDirectory)/PowerShell'
  - group: 'mscodehub-code-read-akv'
  - name: ob_tipsign_enabled
    value: true # Enable TiP sign
  steps:
  - checkout: self ## the global setting on lfs didn't work
    lfs: false

  - template: release-SetReleaseTagandContainerName.yml
  
  - pwsh: |
      $packageVersion = '$(ReleaseTag)'.ToLowerInvariant() -replace '^v',''
      $vstsCommandString = "vso[task.setvariable variable=packageVersion]$packageVersion"
      Write-Host "sending " + $vstsCommandString
      Write-Host "##$vstsCommandString"
    displayName: Set Package version
  
  - pwsh: |
      $branch = 'mirror-target'
      $gitArgs = "clone",
      "--verbose",
      "--branch",
      "$branch",
      "https://$(mscodehubCodeReadPat)@mscodehub.visualstudio.com/PowerShellCore/_git/Internal-PowerShellTeam-Tools",
      '$(Pipeline.Workspace)/tools'
      $gitArgs | Write-Verbose -Verbose
      git $gitArgs
    displayName: Clone Internal-PowerShellTeam-Tools from MSCodeHub

  - pwsh: |
      Get-ChildItem Env: | Out-String -Stream | write-Verbose -Verbose
    displayName: 'Capture Environment Variables'

  - pwsh: |
      Get-ChildItem '$(Pipeline.Workspace)' -Recurse | Out-String -Stream | write-Verbose -Verbose
      Get-ChildItem '$(Build.SourcesDirectory)'
    displayName: 'Capture Workspace'

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.12.7'
    inputs:
      versionSpec: 3.12.7

  - task: PipAuthenticate@1
    inputs:
      artifactFeeds: 'msazure-Compute-PMC@Release'
      pythonDownloadServiceConnections: pmcDownload
    displayName: 'Pip Authenticate'

  - pwsh: |
      $ev2SpecsFolder = "$(repoRoot)/.pipelines/EV2Specs"
      $shellExtensionBundleDir = "$ev2SpecsFolder/ServiceGroupRoot/Shell/Run"

      Write-Verbose -Verbose "Download pmc-cli to folder without installing it"
      $pythonDlFolderPath = Join-Path -Path $shellExtensionBundleDir -ChildPath "python_dl"
      New-Item -Path $pythonDlFolderPath
      pip3 --version
      pip3 download -d $pythonDlFolderPath pmc-cli -v
      $pipExePath = Join-Path -Path "C:\__t\Python\3.12.7\x64\Scripts" -ChildPath "pip3.exe"
      $pipExePathExists = Test-Path $pipExePath
      Write-Verbose -Verbose "pip3 path exists: $pipExePathExists"
      Get-ChildItem "C:\__t\Python\3.12.7\x64\Scripts"

      New-Item -Path "myPythonPkg"
      & 'C:\__t\Python\3.12.7\x64\Scripts\pip3.exe' download pmc-cli -d myPythonPkg 
      Write-Verbose -Verbose "trying gci"
      Get-ChildItem $pythonDlFolderPath
      Write-Verbose -Verbose "done pip download"
    displayName: 'Download pmc-cli package'

  - pwsh: |
      Write-Verbose -Verbose "Copy built .deb packages"
      # assuming ESRP signed packages are here
      # TODO: either copy packages to a folder and .tar it all up- i believe there's a size limit
      # so option 2: make a .tar.gz file and pass it the way I do for images
    displayName: 'Copy signed .deb packages - probably to a .tar.gz to pass as a file var'

  - pwsh: |
      $pathToEV2Folder = Join-Path -Path '$(repoRoot)/.pipelines' -ChildPath 'EV2Specs'
      $pathToServiceGroupRootFolder = Join-Path $pathToEV2Folder -ChildPath 'ServiceGroupRoot'
      $pathToParametersFolder = Join-Path -Path $pathToServiceGroupRootFolder -ChildPath 'Parameters'
      New-Item -Path $pathToParametersFolder -ItemType Directory
      $pathToPMCMetadataFile = Join-Path -Path $pathToParametersFolder -ChildPath 'PmcMetadata.json'

      $metadata = Get-Content -Path "$(repoRoot)/tools/metadata.json" -Raw | ConvertFrom-Json
      $skipPublishVar = '${{ parameters.skipPublish }}'
      $metadataHash = @{}
      $metadataHash["ReleaseTag"] = "$(ReleaseTag)"
      $metadataHash["AadClientId"] = "$(PmcCliClientID)"
      $metadataHash["BlobFolderName"] = "$(ReleaseTag)"
      $metadataHash["LTS"] = $metadata.LTSRelease.Latest
      $metadataHash["ForProduction"] = $true
      $metadataHash["SkipPublish"] = $skipPublishVar

      $metadataHash | ConvertTo-Json | Out-File $pathToPMCMetadataFile

      Write-Verbose -Verbose "Copy mapping.json file to EV2Specs folder. file path at path $mappingFilePath exists: $mappingFilePathExists"
      $mappingFilePath = Join-Path -Path '$(System.DefaultWorkingDirectory)/tools/packages.microsoft.com' -ChildPath 'mapping.json'
      $mappingFilePathExists = Test-Path $mappingFilePath
      $mappingFileEV2Path = Join-Path -Path $pathToParametersFolder -ChildPath "mapping.json"
      Copy-Item -Path $mappingFilePath -Destination $mappingFileEV2Path
    displayName: 'Create pmcScriptMetadata.json and mapping.json file'

  - pwsh: |
      $srcPath = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot' -ChildPath 'Shell'
      $pathToRunTarFile = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot/Shell' -ChildPath "Run.tar"
      tar -cvf $pathToRunTarFile -C $srcPath ./Run
      # TODO: ensure this has: Run.ps1, settings.toml, python_dl
      # tar cvf pmc_packages.tar start.sh settings.toml packages python_dl
    displayName: 'Create archive for the shell extension'

  - task: onebranch.pipeline.signing@1
    displayName: Sign Run.ps1
    inputs:
      command: 'sign'
      signing_profile: 'tipsign' # external_distribution
      files_to_sign: '*.ps1'
      search_root: '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot/Shell/Run'

  - pwsh: |
      $srcPath = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot' -ChildPath 'Shell'
      $pathToRunTarFile = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot/Shell' -ChildPath "Run.tar"
      tar -cvf $pathToRunTarFile -C $srcPath ./Run
    displayName: 'Compress Run script into tar file as needed for EV2 Shell extension'

  # - task: CopyFiles@2
  #   inputs:
  #     Contents: '$(Pipeline.Workspace)/tools/packages.microsoft.com-v4/**' 
  #     TargetFolder: 'EV2Specs/ServiceGroupRoot/tools'

  - task: CopyFiles@2
    inputs:
      Contents: 'EV2Specs/**'
      TargetFolder: $(ob_outputDirectory)
