stages:
- stage: 'Prod_Release'
  displayName: 'Deploy packages to PMC with EV2'
  dependsOn:
  - PrepForEV2
  variables:
    - name: ob_release_environment
      value: "Production"
    - name: repoRoot
      value: $(Build.SourcesDirectory)
  jobs:
  - job: Prod_ReleaseJob
    displayName: Publish to PMC
    pool:
      type: release

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: drop_PrepForEV2_CopyEv2FilesToArtifact
      displayName: 'Download drop_PrepForEV2_CopyEv2FilesToArtifact artifact that has all files needed'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
      displayName: 'Download to get EV2 Files'

    - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
      displayName: 'Ev2: Push to PMC'
      inputs:
        UseServerMonitorTask: true
        EndpointProviderType: ApprovalService
        ApprovalServiceEnvironment: Production
        ServiceRootPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot'
        RolloutSpecPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot/RolloutSpec.json'
