stages:
- stage: PrepForEV2
  displayName: 'Copy and prep all files needed for EV2 stage'
  jobs:
  - job: CopyEV2FilesToArtifact
    displayName: 'Copy EV2 Files to Artifact'
    pool:
      type: linux
    variables:
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
    - name: repoRoot
      value: '$(Build.SourcesDirectory)/PowerShell'
    - name: ev2ServiceGroupRootFolder
      value: '$(Build.SourcesDirectory)/PowerShell/.pipelines/EV2Specs/ServiceGroupRoot'
    - name: ev2ParametersFolder
      value: '$(Build.SourcesDirectory)/PowerShell/.pipelines/EV2Specs/ServiceGroupRoot/Parameters'
    - group: 'mscodehub-code-read-akv'
    - group: 'packages.microsoft.com'
    - name: ob_sdl_credscan_suppressionsFile
      value: $(Build.SourcesDirectory)\PowerShell\.config\suppress.json
    steps:
    - checkout: self ## the global setting on lfs didn't work
      lfs: false
      env:
        ob_restore_phase: true

    - template: release-SetReleaseTagandContainerName.yml
      parameters:
        restorePhase: true

    - pwsh: |
        Get-ChildItem Env: | Out-String -Stream | write-Verbose -Verbose
      displayName: 'Capture Environment Variables'
      env:
        ob_restore_phase: true

    - pwsh: |
        Get-ChildItem '$(Build.SourcesDirectory)'
      displayName: 'Capture BuildDirectory'
      env:
        ob_restore_phase: true

    - pwsh: |
        $attemptPath = Test-Path '$(Pipeline.Workspace)/PowerShell/.pipelines'
        Write-Verbose -Verbose "attempt pipeline workspace: $attemptPath"
        Get-ChildItem '$(Pipeline.Workspace)' -Recurse | Out-String -Stream | write-Verbose -Verbose
      displayName: 'Capture Workspace'
      env:
        ob_restore_phase: true

    - pwsh: |
        $path = '$(Build.SourcesDirectory)/PowerShell/.pipelines'
        $attemptPath = Test-Path $path
        Write-Verbose -Verbose "path exists pre: $path : $attemptPath"
        New-Item -Path '$(ev2ParametersFolder)' -ItemType Directory
      displayName: 'Create Parameters folder under EV2Specs folder'
      env:
        ob_restore_phase: true

    - task: PipAuthenticate@1
      inputs:
        artifactFeeds: 'PowerShellCore/PowerShellCore_PublicPackages'
      displayName: 'Pip Authenticate'
      env:
        ob_restore_phase: true

    - pwsh: |
        python3 -m pip install --upgrade pip
        pip --version --verbose

        Write-Verbose -Verbose "Download pmc-cli to folder without installing it"
        $ev2SpecsFolder = "$(repoRoot)/.pipelines/EV2Specs"
        $shellExtensionBundleDir = "$ev2SpecsFolder/ServiceGroupRoot/Shell/Run"
        $pythonDlFolderPath = Join-Path -Path $shellExtensionBundleDir -ChildPath "python_dl"
        pip download -d $pythonDlFolderPath pmc-cli --platform=manylinux_2_17_x86_64 --only-binary=:all: --verbose
      displayName: 'Download pmc-cli package'
      env:
        ob_restore_phase: true

    - download: PSPackagesOfficial
      artifact: 'drop_linux_package_deb'
      displayName: 'Download artifact containing .deb_amd64.deb file from PSPackagesOfficial triggering pipeline'
      env:
        ob_restore_phase: true

    - download: PSPackagesOfficial
      artifact: 'drop_linux_package_rpm'
      displayName: 'Download artifact containing .rh.x64_86.rpm file from PSPackagesOfficial triggering pipeline'
      env:
        ob_restore_phase: true

    - download: PSPackagesOfficial
      artifact: 'drop_linux_package_mariner_x64'
      displayName: 'Download artifact containing .cm.x86_64.rpm file from PSPackagesOfficial triggering pipeline'
      env:
        ob_restore_phase: true

    - download: PSPackagesOfficial
      artifact: 'drop_linux_package_mariner_arm64'
      displayName: 'Download artifact containing .cm.aarch64.rpm file from PSPackagesOfficial triggering pipeline'
      env:
        ob_restore_phase: true

    - pwsh: |
        Write-Verbose -Verbose "Copy ESRP signed .deb and .rpm packages"
        $downloadedPipelineFolder = Join-Path '$(Pipeline.Workspace)' -ChildPath 'PSPackagesOfficial'
        $srcFilesFolder = Join-Path -Path '$(Pipeline.Workspace)' -ChildPath 'SourceFiles'
        New-Item -Path $srcFilesFolder -ItemType Directory
        $packagesFolder = Join-Path -Path $srcFilesFolder -ChildPath 'packages'
        New-Item -Path $packagesFolder -ItemType Directory

        $packageFiles = Get-ChildItem -Path $downloadedPipelineFolder -Recurse -Directory -Filter "drop_*" | Get-ChildItem -File -Include *.deb, *.rpm
        foreach ($file in $packageFiles)
        {
          Write-Verbose -Verbose "copying file: $($file.FullName)"
          Copy-Item -Path $($file.FullName) -Destination $packagesFolder -Verbose
        }

        $packagesTarGzDestination = Join-Path -Path '$(ev2ParametersFolder)' -ChildPath 'packages.tar.gz'
        tar -czvf $packagesTarGzDestination -C $packagesFolder .
      displayName: 'Copy signed .deb and .rpm packages to .tar.gz to pass as a file var to shell extension'
      env:
        ob_restore_phase: true

    - pwsh: |
        $pathToJsonFile = Join-Path -Path '$(ev2ServiceGroupRootFolder)' -ChildPath 'RolloutSpec.json'
        $content = Get-Content -Path $pathToJsonFile | ConvertFrom-Json
        $content.RolloutMetadata.Notification.Email.To = '$(myEV2SupportEmail)'
        Remove-Item -Path $pathToJsonFile
        $content | ConvertTo-Json -Depth 4 | Out-File $pathToJsonFile
      displayName: 'Replace values in RolloutSpecPath.json'
      env:
        ob_restore_phase: true

    - pwsh: |
        $pathToJsonFile = Join-Path -Path '$(ev2ServiceGroupRootFolder)' -ChildPath 'UploadLinux.Rollout.json'
        $content = Get-Content -Path $pathToJsonFile | ConvertFrom-Json

        $identityString = "/subscriptions/$(mySubscription)/resourcegroups/$(myResourceGroup)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$(myMIName)"
        $content.shellExtensions.launch.identity.userAssignedIdentities[0] = $identityString

        Remove-Item -Path $pathToJsonFile
        $content | ConvertTo-Json -Depth 6 | Out-File $pathToJsonFile
      displayName: 'Replace values in UploadLinux.Rollout.json file'
      env:
        ob_restore_phase: true

    - pwsh: |
        # TODO: ensure myResourceGroup and mySubscription are variables in library variable group
        $pathToJsonFile = Join-Path -Path '$(ev2ServiceGroupRootFolder)' -ChildPath 'ServiceModel.json'
        $content = Get-Content -Path $pathToJsonFile | ConvertFrom-Json
        $content.ServiceResourceGroups[0].AzureResourceGroupName = '$(myResourceGroup)'
        $content.ServiceResourceGroups[0].AzureSubscriptionId = '$(mySubscription)'

        Remove-Item -Path $pathToJsonFile
        $content | ConvertTo-Json -Depth 9 | Out-File $pathToJsonFile
      displayName: 'Replace values in ServiceModel.json'
      env:
        ob_restore_phase: true

    - task: onebranch.pipeline.signing@1
      inputs:
        command: 'sign'
        signing_profile: external_distribution
        files_to_sign: '*.ps1'
        search_root: '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot/Shell/Run'
      displayName: Sign Run.ps1
  
    - pwsh: |
        # folder to tar (ie /Run) must have: Run.ps1 and any other folders/files you want extracted
        $srcPath = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot' -ChildPath 'Shell'
        $pathToRunTarFile = Join-Path '$(repoRoot)/.pipelines/EV2Specs/ServiceGroupRoot/Shell' -ChildPath "Run.tar"
        tar -cvf $pathToRunTarFile -C $srcPath ./Run
      displayName: 'Create archive for the shell extension'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(repoRoot)/.pipelines'
        Contents: 'EV2Specs/**'
        TargetFolder: $(ob_outputDirectory)

- stage: 'Test_Release'
  displayName: 'Test deploy packages to PMC with EV2'
  dependsOn:
  - PrepForEV2
  variables:
    - name: ob_release_environment
      value: "Test"
    - name: repoRoot
      value: $(Build.SourcesDirectory)
  jobs:
  - job: Test_ReleaseJob
    displayName: Publish to PMC
    pool:
      type: release

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: drop_PrepForEV2_CopyEv2FilesToArtifact
      displayName: 'Download drop_PrepForEV2_CopyEv2FilesToArtifact artifact that has all files needed'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
      displayName: 'Download to get EV2 Files'

    - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
      displayName: 'Ev2: Push to PMC'
      inputs:
        UseServerMonitorTask: true
        ConnectedServiceName: 'pmc-ev2-deployment'
        ServiceRootPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot'
        RolloutSpecPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot/RolloutSpec.json'
      
- stage: 'Prod_Release'
  displayName: 'Deploy packages to PMC with EV2'
  dependsOn:
  - PrepForEV2
  variables:
    - name: ob_release_environment
      value: "Production"
    - name: repoRoot
      value: $(Build.SourcesDirectory)
  jobs:
  - job: Prod_ReleaseJob
    displayName: Publish to PMC
    pool:
      type: release

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: drop_PrepForEV2_CopyEv2FilesToArtifact
      displayName: 'Download drop_PrepForEV2_CopyEv2FilesToArtifact artifact that has all files needed'

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
      displayName: 'Download to get EV2 Files'

    - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
      displayName: 'Ev2: Push to PMC'
      inputs:
        UseServerMonitorTask: true
        EndpointProviderType: ApprovalService
        ApprovalServiceEnvironment: Production
        ServiceRootPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot'
        RolloutSpecPath: '$(Pipeline.Workspace)/drop_PrepForEV2_CopyEV2FilesToArtifact/EV2Specs/ServiceGroupRoot/RolloutSpec.json'
