[ClassVersion("1.0.0"), FriendlyName("nxUser")]
class MSFT_nxUserResource : OMI_BaseResource
{
       [Key] string UserName;
       [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
       [write] string FullName;
       [write] string Description;
       [write] string Password;
       [write] boolean Disabled;
       [write] boolean PasswordChangeRequired;
       [write] string HomeDirectory;
       [write] string GroupID;
       [read] string UserID;

};
