[ClassVersion("1.0.0"), FriendlyName("nxGroup")]
class MSFT_nxGroupResource:OMI_BaseResource
{
  [Key] string GroupName;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write] string Members[];
  [write] string MembersToInclude[];
  [write] string MembersToExclude[];
  [write] string PreferredGroupID;
  [read] string GroupID;

};
