ARG VARIANT=preview
FROM mcr.microsoft.com/devcontainers/dotnet:${VARIANT}

# This is a workaround for https://github.com/microsoft/vscode-remote-release/issues/10934
ADD ./scripts /devcontainer/scripts