//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    internal class ConsoleInfoErrorStrings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal ConsoleInfoErrorStrings() { }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("System.Management.Automation.resources.ConsoleInfoErrorStrings", typeof(ConsoleInfoErrorStrings).GetTypeInfo().Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string BadMonadVersion => ResourceManager.GetString("BadMonadVersion", resourceCulture);
        internal static string ConsoleLoadFailure => ResourceManager.GetString("ConsoleLoadFailure", resourceCulture);
        internal static string PSSnapInLoadFailure => ResourceManager.GetString("PSSnapInLoadFailure", resourceCulture);
        internal static string PSSnapInLoadWarning => ResourceManager.GetString("PSSnapInLoadWarning", resourceCulture);
        internal static string PSSnapInAssemblyNameMismatch => ResourceManager.GetString("PSSnapInAssemblyNameMismatch", resourceCulture);
        internal static string PSSnapInDuplicateCmdlets => ResourceManager.GetString("PSSnapInDuplicateCmdlets", resourceCulture);
        internal static string PSSnapInDuplicateProviders => ResourceManager.GetString("PSSnapInDuplicateProviders", resourceCulture);
        internal static string AddPSSnapInBadMonadVersion => ResourceManager.GetString("AddPSSnapInBadMonadVersion", resourceCulture);
        internal static string FileExistsNoClobber => ResourceManager.GetString("FileExistsNoClobber", resourceCulture);
        internal static string ConfigurationFileDoesNotExist => ResourceManager.GetString("ConfigurationFileDoesNotExist", resourceCulture);
        internal static string NotConfigurationFile => ResourceManager.GetString("NotConfigurationFile", resourceCulture);
    }
}
