//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    internal class ParserStrings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal ParserStrings() { }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("System.Management.Automation.resources.ParserStrings", typeof(ParserStrings).Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

    // Resource keys as static string properties
    public static string TypeNotFound => ResourceManager.GetString("TypeNotFound", resourceCulture);
    public static string TypeNotFoundWithMessage => ResourceManager.GetString("TypeNotFoundWithMessage", resourceCulture);
    public static string IncompleteString => ResourceManager.GetString("IncompleteString", resourceCulture);
    public static string InvalidUnicodeEscapeSequence => ResourceManager.GetString("InvalidUnicodeEscapeSequence", resourceCulture);
    public static string InvalidUnicodeEscapeSequenceValue => ResourceManager.GetString("InvalidUnicodeEscapeSequenceValue", resourceCulture);
    public static string MissingUnicodeEscapeSequenceTerminator => ResourceManager.GetString("MissingUnicodeEscapeSequenceTerminator", resourceCulture);
    public static string TooManyDigitsInUnicodeEscapeSequence => ResourceManager.GetString("TooManyDigitsInUnicodeEscapeSequence", resourceCulture);
    public static string ReferenceNeedsToBeByItselfInTypeConstraint => ResourceManager.GetString("ReferenceNeedsToBeByItselfInTypeConstraint", resourceCulture);
    public static string ReferenceNeedsToBeLastTypeInTypeConversion => ResourceManager.GetString("ReferenceNeedsToBeLastTypeInTypeConversion", resourceCulture);
    public static string ReferenceNeedsToBeByItselfInTypeSequence => ResourceManager.GetString("ReferenceNeedsToBeByItselfInTypeSequence", resourceCulture);
    public static string BadNumericConstant => ResourceManager.GetString("BadNumericConstant", resourceCulture);
    public static string InvalidRegularExpression => ResourceManager.GetString("InvalidRegularExpression", resourceCulture);
    public static string EmptyVariableReference => ResourceManager.GetString("EmptyVariableReference", resourceCulture);
    public static string InvalidVariableReference => ResourceManager.GetString("InvalidVariableReference", resourceCulture);
    public static string InvokeMethodOnNull => ResourceManager.GetString("InvokeMethodOnNull", resourceCulture);
    public static string MethodNotFound => ResourceManager.GetString("MethodNotFound", resourceCulture);
    public static string ParameterizedPropertyAssignmentFailed => ResourceManager.GetString("ParameterizedPropertyAssignmentFailed", resourceCulture);
    public static string UnexpectedToken => ResourceManager.GetString("UnexpectedToken", resourceCulture);
    public static string SplattingNotPermitted => ResourceManager.GetString("SplattingNotPermitted", resourceCulture);
    public static string InvalidParameter => ResourceManager.GetString("InvalidParameter", resourceCulture);
    public static string MissingExpression => ResourceManager.GetString("MissingExpression", resourceCulture);
    public static string BadExpression => ResourceManager.GetString("BadExpression", resourceCulture);
    public static string ParameterRequiresArgument => ResourceManager.GetString("ParameterRequiresArgument", resourceCulture);
    public static string ParameterCannotHaveArgument => ResourceManager.GetString("ParameterCannotHaveArgument", resourceCulture);
    public static string DuplicateFormalParameter => ResourceManager.GetString("DuplicateFormalParameter", resourceCulture);
    public static string MissingArgument => ResourceManager.GetString("MissingArgument", resourceCulture);
    public static string SplattingNotPermittedInArgumentList => ResourceManager.GetString("SplattingNotPermittedInArgumentList", resourceCulture);
    public static string MissingFileSpecification => ResourceManager.GetString("MissingFileSpecification", resourceCulture);
    public static string RedirectionNotSupported => ResourceManager.GetString("RedirectionNotSupported", resourceCulture);
    public static string RedirectionFailed => ResourceManager.GetString("RedirectionFailed", resourceCulture);
    public static string ExpressionsMustBeFirstInPipeline => ResourceManager.GetString("ExpressionsMustBeFirstInPipeline", resourceCulture);
    public static string EmptyPipeElement => ResourceManager.GetString("EmptyPipeElement", resourceCulture);
    public static string InvalidLeftHandSide => ResourceManager.GetString("InvalidLeftHandSide", resourceCulture);
    public static string AddHashTableToNonHashTable => ResourceManager.GetString("AddHashTableToNonHashTable", resourceCulture);
    public static string IsOperatorRequiresType => ResourceManager.GetString("IsOperatorRequiresType", resourceCulture);
    public static string AsOperatorRequiresType => ResourceManager.GetString("AsOperatorRequiresType", resourceCulture);
    public static string FormatError => ResourceManager.GetString("FormatError", resourceCulture);
    public static string BadOperatorArgument => ResourceManager.GetString("BadOperatorArgument", resourceCulture);
    public static string OperatorFailed => ResourceManager.GetString("OperatorFailed", resourceCulture);
    public static string BadReplaceArgument => ResourceManager.GetString("BadReplaceArgument", resourceCulture);
    public static string ExpectedValueExpression => ResourceManager.GetString("ExpectedValueExpression", resourceCulture);
    public static string OperatorRequiresVariableOrProperty => ResourceManager.GetString("OperatorRequiresVariableOrProperty", resourceCulture);
    public static string OrderedAttributeOnlyOnHashLiteralNode => ResourceManager.GetString("OrderedAttributeOnlyOnHashLiteralNode", resourceCulture);
    public static string MissingArrayIndexExpression => ResourceManager.GetString("MissingArrayIndexExpression", resourceCulture);
    public static string MissingPropertyName => ResourceManager.GetString("MissingPropertyName", resourceCulture);
    public static string PropertyNotFound => ResourceManager.GetString("PropertyNotFound", resourceCulture);
    public static string PropertyNotFoundStrict => ResourceManager.GetString("PropertyNotFoundStrict", resourceCulture);
    public static string NullArrayIndex => ResourceManager.GetString("NullArrayIndex", resourceCulture);
    public static string NullArray => ResourceManager.GetString("NullArray", resourceCulture);
    public static string CannotIndex => ResourceManager.GetString("CannotIndex", resourceCulture);
    public static string CannotIndexWithByRefLikeReturnType => ResourceManager.GetString("CannotIndexWithByRefLikeReturnType", resourceCulture);
    public static string ArrayHasTooManyDimensions => ResourceManager.GetString("ArrayHasTooManyDimensions", resourceCulture);
    public static string ArraySliceAssignmentFailed => ResourceManager.GetString("ArraySliceAssignmentFailed", resourceCulture);
    public static string NeedMultidimensionalIndex => ResourceManager.GetString("NeedMultidimensionalIndex", resourceCulture);
    public static string IndexOutOfRange => ResourceManager.GetString("IndexOutOfRange", resourceCulture);
    public static string MissingExpressionAfterToken => ResourceManager.GetString("MissingExpressionAfterToken", resourceCulture);
    public static string IncompleteDollarVariableReference => ResourceManager.GetString("IncompleteDollarVariableReference", resourceCulture);
    public static string IncompleteDollarSubexpressionReference => ResourceManager.GetString("IncompleteDollarSubexpressionReference", resourceCulture);
    public static string UnexpectedUnaryOperator => ResourceManager.GetString("UnexpectedUnaryOperator", resourceCulture);
    public static string NonExistingVariableReference => ResourceManager.GetString("NonExistingVariableReference", resourceCulture);
    public static string VariableIsUndefined => ResourceManager.GetString("VariableIsUndefined", resourceCulture);
    public static string DuplicateKeyInHashLiteral => ResourceManager.GetString("DuplicateKeyInHashLiteral", resourceCulture);
    public static string DuplicateNamedArgument => ResourceManager.GetString("DuplicateNamedArgument", resourceCulture);
    public static string OperatorRequiresNumber => ResourceManager.GetString("OperatorRequiresNumber", resourceCulture);
    public static string ExpectedExpression => ResourceManager.GetString("ExpectedExpression", resourceCulture);
    public static string MissingEqualsInHashLiteral => ResourceManager.GetString("MissingEqualsInHashLiteral", resourceCulture);
    public static string MissingStatementInHashLiteral => ResourceManager.GetString("MissingStatementInHashLiteral", resourceCulture);
    public static string MissingExpressionInNamedArgument => ResourceManager.GetString("MissingExpressionInNamedArgument", resourceCulture);
    public static string MissingPropertyTerminator => ResourceManager.GetString("MissingPropertyTerminator", resourceCulture);
    public static string MissingExpressionAfterOperator => ResourceManager.GetString("MissingExpressionAfterOperator", resourceCulture);
    public static string IfStatementMissingCondition => ResourceManager.GetString("IfStatementMissingCondition", resourceCulture);
    public static string MissingStatementBlock => ResourceManager.GetString("MissingStatementBlock", resourceCulture);
    public static string MissingStatementBlockAfterElse => ResourceManager.GetString("MissingStatementBlockAfterElse", resourceCulture);
    public static string FileReadError => ResourceManager.GetString("FileReadError", resourceCulture);
    public static string FileOpenError => ResourceManager.GetString("FileOpenError", resourceCulture);
    public static string FileNotFound => ResourceManager.GetString("FileNotFound", resourceCulture);
    public static string AmbiguousPath => ResourceManager.GetString("AmbiguousPath", resourceCulture);
    public static string KeywordParameterReservedForFutureUse => ResourceManager.GetString("KeywordParameterReservedForFutureUse", resourceCulture);
    public static string MissingFilenameOption => ResourceManager.GetString("MissingFilenameOption", resourceCulture);
    public static string InvalidFilenameOption => ResourceManager.GetString("InvalidFilenameOption", resourceCulture);
    public static string InvalidSwitchFlag => ResourceManager.GetString("InvalidSwitchFlag", resourceCulture);
    public static string InvalidForeachFlag => ResourceManager.GetString("InvalidForeachFlag", resourceCulture);
    public static string PipelineValueRequired => ResourceManager.GetString("PipelineValueRequired", resourceCulture);
    public static string MissingSwitchConditionExpression => ResourceManager.GetString("MissingSwitchConditionExpression", resourceCulture);
    public static string MultipleSwitchDefaultClauses => ResourceManager.GetString("MultipleSwitchDefaultClauses", resourceCulture);
    public static string MissingSwitchStatementClause => ResourceManager.GetString("MissingSwitchStatementClause", resourceCulture);
    public static string MissingForeachExpression => ResourceManager.GetString("MissingForeachExpression", resourceCulture);
    public static string MissingForeachStatement => ResourceManager.GetString("MissingForeachStatement", resourceCulture);
    public static string OnlyOneParameterListAllowed => ResourceManager.GetString("OnlyOneParameterListAllowed", resourceCulture);
    public static string NotADefinedOperationForType => ResourceManager.GetString("NotADefinedOperationForType", resourceCulture);
    public static string BadEnumeration => ResourceManager.GetString("BadEnumeration", resourceCulture);
    public static string COMException => ResourceManager.GetString("COMException", resourceCulture);
    public static string InvalidComObjectException => ResourceManager.GetString("InvalidComObjectException", resourceCulture);
    // ... (add all remaining keys from ParserStrings.resx as needed)
    }
}
