//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    internal static class SessionStateStrings
    {
        public static string InvalidProviderInfo => nameof(InvalidProviderInfo);
        public static string InvalidProviderInfoNull => nameof(InvalidProviderInfoNull);
        public static string GetItemProviderException => nameof(GetItemProviderException);
        public static string GetItemDynamicParametersProviderException => nameof(GetItemDynamicParametersProviderException);
        public static string SetItemProviderException => nameof(SetItemProviderException);
        public static string SetItemDynamicParametersProviderException => nameof(SetItemDynamicParametersProviderException);
        public static string ClearItemProviderException => nameof(ClearItemProviderException);
        public static string InvokeDefaultActionProviderException => nameof(InvokeDefaultActionProviderException);
        public static string InvokeDefaultActionDynamicParametersProviderException => nameof(InvokeDefaultActionDynamicParametersProviderException);
        public static string ItemExistsProviderException => nameof(ItemExistsProviderException);
        public static string ItemExistsDynamicParametersProviderException => nameof(ItemExistsDynamicParametersProviderException);
        public static string IsValidPathProviderException => nameof(IsValidPathProviderException);
        public static string IsItemContainerProviderException => nameof(IsItemContainerProviderException);
        public static string RemoveItemProviderException => nameof(RemoveItemProviderException);
        public static string GetChildrenProviderException => nameof(GetChildrenProviderException);
        public static string GetChildrenDynamicParametersProviderException => nameof(GetChildrenDynamicParametersProviderException);
        public static string GetChildNamesProviderException => nameof(GetChildNamesProviderException);
        public static string GetChildNamesDynamicParametersProviderException => nameof(GetChildNamesDynamicParametersProviderException);
        public static string RenameItemProviderException => nameof(RenameItemProviderException);
        public static string RenameItemDynamicParametersProviderException => nameof(RenameItemDynamicParametersProviderException);
        public static string NewItemProviderException => nameof(NewItemProviderException);
        public static string NewItemDynamicParametersProviderException => nameof(NewItemDynamicParametersProviderException);
        public static string HasChildItemsProviderException => nameof(HasChildItemsProviderException);
        public static string CopyItemProviderException => nameof(CopyItemProviderException);
        public static string CopyItemDynamicParametersProviderException => nameof(CopyItemDynamicParametersProviderException);
        public static string GetParentPathProviderException => nameof(GetParentPathProviderException);
        public static string NormalizeRelativePathProviderException => nameof(NormalizeRelativePathProviderException);
    }
}
