//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Management.Automation
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    internal class TypesXmlStrings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal TypesXmlStrings() { }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("System.Management.Automation.resources.TypesXmlStrings", typeof(TypesXmlStrings).GetTypeInfo().Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string FileLineError => ResourceManager.GetString("FileLineError", resourceCulture);
        internal static string FileLineTypeError => ResourceManager.GetString("FileLineTypeError", resourceCulture);
        internal static string NotMoreThanOnceOne => ResourceManager.GetString("NotMoreThanOnceOne", resourceCulture);
        internal static string UnknownNode => ResourceManager.GetString("UnknownNode", resourceCulture);
        internal static string NodeShouldNotHaveInnerText => ResourceManager.GetString("NodeShouldNotHaveInnerText", resourceCulture);
        internal static string NodeShouldHaveInnerText => ResourceManager.GetString("NodeShouldHaveInnerText", resourceCulture);
        internal static string NodeNotFoundOnce => ResourceManager.GetString("NodeNotFoundOnce", resourceCulture);
        internal static string TypeNodeShouldHaveMembersOrTypeConverters => ResourceManager.GetString("TypeNodeShouldHaveMembersOrTypeConverters", resourceCulture);
        internal static string UnableToInstantiateTypeConverter => ResourceManager.GetString("UnableToInstantiateTypeConverter", resourceCulture);
        internal static string UnableToInstantiateTypeAdapter => ResourceManager.GetString("UnableToInstantiateTypeAdapter", resourceCulture);
        internal static string InvalidAdaptedType => ResourceManager.GetString("InvalidAdaptedType", resourceCulture);
        internal static string TypeConverterAlreadyPresent => ResourceManager.GetString("TypeConverterAlreadyPresent", resourceCulture);
        internal static string TypeAdapterAlreadyPresent => ResourceManager.GetString("TypeAdapterAlreadyPresent", resourceCulture);
        internal static string TypeIsNotTypeConverter => ResourceManager.GetString("TypeIsNotTypeConverter", resourceCulture);
        internal static string TypeIsNotTypeAdapter => ResourceManager.GetString("TypeIsNotTypeAdapter", resourceCulture);
        internal static string DuplicateMember => ResourceManager.GetString("DuplicateMember", resourceCulture);
        internal static string ReservedNameMember => ResourceManager.GetString("ReservedNameMember", resourceCulture);
        internal static string Exception => ResourceManager.GetString("Exception", resourceCulture);
        internal static string ScriptPropertyShouldHaveGetterOrSetter => ResourceManager.GetString("ScriptPropertyShouldHaveGetterOrSetter", resourceCulture);
        internal static string CodePropertyShouldHaveGetterOrSetter => ResourceManager.GetString("CodePropertyShouldHaveGetterOrSetter", resourceCulture);
        internal static string FileError => ResourceManager.GetString("FileError", resourceCulture);
        internal static string ValueShouldBeTrueOrFalse => ResourceManager.GetString("ValueShouldBeTrueOrFalse", resourceCulture);
        internal static string IsHiddenNotSupported => ResourceManager.GetString("IsHiddenNotSupported", resourceCulture);
        internal static string FileNotFound => ResourceManager.GetString("FileNotFound", resourceCulture);
        internal static string DuplicateFile => ResourceManager.GetString("DuplicateFile", resourceCulture);
        internal static string CannotFindRegistryKey => ResourceManager.GetString("CannotFindRegistryKey", resourceCulture);
        internal static string CannotFindRegistryKeyPath => ResourceManager.GetString("CannotFindRegistryKeyPath", resourceCulture);
        internal static string EntryShouldBeMshXml => ResourceManager.GetString("EntryShouldBeMshXml", resourceCulture);
        internal static string ValidationException => ResourceManager.GetString("ValidationException", resourceCulture);
        internal static string MemberShouldBeNote => ResourceManager.GetString("MemberShouldBeNote", resourceCulture);
        internal static string ErrorConvertingNote => ResourceManager.GetString("ErrorConvertingNote", resourceCulture);
        internal static string MemberShouldNotBePresent => ResourceManager.GetString("MemberShouldNotBePresent", resourceCulture);
        internal static string MemberShouldHaveType => ResourceManager.GetString("MemberShouldHaveType", resourceCulture);
        internal static string MemberMustBePresent => ResourceManager.GetString("MemberMustBePresent", resourceCulture);
        internal static string SerializationSettingsIgnored => ResourceManager.GetString("SerializationSettingsIgnored", resourceCulture);
        internal static string NotAStandardMember => ResourceManager.GetString("NotAStandardMember", resourceCulture);
        internal static string TypeFileNotRooted => ResourceManager.GetString("TypeFileNotRooted", resourceCulture);
        internal static string SharedTypeTableCannotBeUpdated => ResourceManager.GetString("SharedTypeTableCannotBeUpdated", resourceCulture);
        internal static string TypeTableLoadErrors => ResourceManager.GetString("TypeTableLoadErrors", resourceCulture);
        internal static string TypeDataTypeError => ResourceManager.GetString("TypeDataTypeError", resourceCulture);
        internal static string TypeDataShouldHaveValue => ResourceManager.GetString("TypeDataShouldHaveValue", resourceCulture);
        internal static string TypeDataShouldNotBeNullOrEmpty => ResourceManager.GetString("TypeDataShouldNotBeNullOrEmpty", resourceCulture);
        internal static string TypeNotFound => ResourceManager.GetString("TypeNotFound", resourceCulture);
        internal static string TypeDataShouldNotBeEmpty => ResourceManager.GetString("TypeDataShouldNotBeEmpty", resourceCulture);
        internal static string TypeTableCannotCoExist => ResourceManager.GetString("TypeTableCannotCoExist", resourceCulture);
    }
}
