[ClassVersion("1.0.0"), FriendlyName("nxArchive")] 
class MSFT_nxArchiveResource : OMI_BaseResource
{
  [Key] string SourcePath;
  [Key] string DestinationPath;
  [write,ValueMap{"ctime", "mtime", "md5"},Values{"ctime", "mtime","md5"}] string Checksum;
  [write] boolean Force;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
		
