SRCS \
	= \
	../src/monad/monad/src/engine/ChildrenCmdletProviderInterfaces.cs \
	../src/monad/monad/src/engine/CmdletFamilyProviderInterfaces.cs \
	../src/monad/monad/src/engine/MshCmdlet.cs \
	../src/monad/monad/src/engine/cmdlet.cs \
	../src/monad/monad/src/engine/CommandBase.cs \
	../src/monad/monad/src/engine/CommandFactory.cs \
	../src/monad/monad/src/engine/CommandParameter.cs \
	../src/monad/monad/src/engine/CommandProcessor.cs \
	../src/monad/monad/src/engine/CommandProcessorBase.cs \
	../src/monad/monad/src/engine/CommonCommandParameters.cs \
	../src/monad/monad/src/engine/ContentCmdletProviderInterfaces.cs \
	../src/monad/monad/src/engine/DriveInterfaces.cs \
	../src/monad/monad/src/engine/EnumExpressionEvaluator.cs \
	../src/monad/monad/src/engine/EnumMinimumDisambiguation.cs \
	../src/monad/monad/src/engine/ErrorPackage.cs \
	../src/monad/monad/src/engine/InvocationInfo.cs \
	../src/monad/monad/src/engine/ItemCmdletProviderInterfaces.cs \
	../src/monad/monad/src/engine/NativeCommand.cs \
	../src/monad/monad/src/engine/PathInterfaces.cs \
	../src/monad/monad/src/engine/ProgressRecord.cs \
	../src/monad/monad/src/engine/InformationRecord.cs \
	../src/monad/monad/src/engine/PropertyCmdletProviderInterfaces.cs \
	../src/monad/monad/src/engine/ProviderInterfaces.cs \
	../src/monad/monad/src/engine/ProxyCommand.cs \
	../src/monad/monad/src/engine/SessionStatePublic.cs \
	../src/monad/monad/src/engine/ScriptCommand.cs \
	../src/monad/monad/src/engine/ScriptCommandProcessor.cs \
	../src/monad/monad/src/engine/UserFeedbackParameters.cs \
	../src/monad/monad/src/engine/VariableInterfaces.cs \
	../src/monad/monad/src/engine/ICommandRuntime.cs \
	../src/monad/monad/src/engine/MshCommandRuntime.cs \
	../src/monad/monad/src/engine/DefaultCommandRuntime.cs \
	../src/monad/monad/src/engine/AliasInfo.cs \
	../src/monad/monad/src/engine/ApplicationInfo.cs \
	../src/monad/monad/src/engine/CmdletInfo.cs \
	../src/monad/monad/src/engine/CmdletParameterBinderController.cs \
	../src/monad/monad/src/engine/CommandDiscovery.cs \
	../src/monad/monad/src/engine/CommandInfo.cs \
	../src/monad/monad/src/engine/CommandPathSearch.cs \
	../src/monad/monad/src/engine/CommandSearcher.cs \
	../src/monad/monad/src/engine/CompiledCommandParameter.cs \
	../src/monad/monad/src/engine/ExternalScriptInfo.cs \
	../src/monad/monad/src/engine/FilterInfo.cs \
	../src/monad/monad/src/engine/FunctionInfo.cs \
	../src/monad/monad/src/engine/ConfigurationInfo.cs \
	../src/monad/monad/src/engine/DscResourceInfo.cs \
	../src/monad/monad/src/engine/GetCommandCommand.cs \
	../src/monad/monad/src/engine/MergedCommandParameterMetadata.cs \
	../src/monad/monad/src/engine/ParameterBinderBase.cs \
	../src/monad/monad/src/engine/ParameterBinderController.cs \
	../src/monad/monad/src/engine/ParameterInfo.cs \
	../src/monad/monad/src/engine/ParameterSetInfo.cs \
	../src/monad/monad/src/engine/ParameterSetPromptingData.cs \
	../src/monad/monad/src/engine/ParameterSetSpecificMetadata.cs \
	../src/monad/monad/src/engine/PositionalCommandParameter.cs \
	../src/monad/monad/src/engine/PseudoParameterBinder.cs \
	../src/monad/monad/src/engine/PseudoParameters.cs \
	../src/monad/monad/src/engine/ReflectionParameterBinder.cs \
	../src/monad/monad/src/engine/ScriptInfo.cs \
	../src/monad/monad/src/engine/scriptparameterbinder.cs \
	../src/monad/monad/src/engine/scriptparameterbindercontroller.cs \
	../src/monad/monad/src/engine/MshSnapinQualifiedName.cs \
	../src/monad/monad/src/engine/TypeMetadata.cs \
	../src/monad/monad/src/engine/WorkflowInfo.cs \
	../src/monad/monad/src/engine/MinishellParameterBinderController.cs \
	../src/monad/monad/src/engine/NativeCommandParameterBinder.cs \
	../src/monad/monad/src/engine/NativeCommandParameterBinderController.cs \
	../src/monad/monad/src/engine/NativeCommandProcessor.cs \
	../src/monad/monad/src/engine/DscResourceSearcher.cs \
	../src/monad/monad/src/engine/Modules/AnalysisCache.cs \
	../src/monad/monad/src/engine/Modules/ExportModuleMemberCommand.cs \
	../src/monad/monad/src/engine/Modules/GetModuleCommand.cs \
	../src/monad/monad/src/engine/Modules/ImportModuleCommand.cs \
	../src/monad/monad/src/engine/Modules/ModuleCmdletBase.cs \
	../src/monad/monad/src/engine/Modules/ModuleIntrinsics.cs \
	../src/monad/monad/src/engine/Modules/ModuleSpecification.cs \
	../src/monad/monad/src/engine/Modules/ModuleUtils.cs \
	../src/monad/monad/src/engine/Modules/NewModuleCommand.cs \
	../src/monad/monad/src/engine/Modules/NewModuleManifestCommand.cs \
	../src/monad/monad/src/engine/Modules/PSModuleInfo.cs \
	../src/monad/monad/src/engine/Modules/RemoteDiscoveryHelper.cs \
	../src/monad/monad/src/engine/Modules/RemoveModuleCommand.cs \
	../src/monad/monad/src/engine/Modules/ScriptAnalysis.cs \
	../src/monad/monad/src/engine/Modules/TestModuleManifestCommand.cs \
	../src/monad/monad/src/engine/AutomationEngine.cs \
	../src/monad/monad/src/engine/EngineIntrinsics.cs \
	../src/monad/monad/src/engine/ExecutionContext.cs \
	../src/monad/monad/src/engine/PSVersionInfo.cs \
	../src/monad/monad/src/engine/EventManager.cs \
	../src/monad/monad/src/engine/ObjectEventRegistrationBase.cs \
	../src/monad/monad/src/engine/debugger/Breakpoint.cs \
	../src/monad/monad/src/engine/debugger/debugger.cs \
	../src/monad/monad/src/engine/CoreAdapter.cs \
	../src/monad/monad/src/engine/ThirdPartyAdapter.cs \
	../src/monad/monad/src/engine/LanguagePrimitives.cs \
	../src/monad/monad/src/engine/NullString.cs \
	../src/monad/monad/src/engine/MshMemberInfo.cs \
	../src/monad/monad/src/engine/MshObject.cs \
	../src/monad/monad/src/engine/TypeTable.cs \
	../src/monad/monad/src/engine/ExtendedTypeSystemException.cs \
	../src/monad/monad/src/engine/MshReference.cs \
	../src/monad/monad/src/engine/WinRT/IInspectable.cs \
	../src/monad/monad/src/help/CabinetAPI.cs \
	../src/monad/monad/src/help/CabinetNativeApi.cs \
	../src/monad/monad/src/engine/hostifaces/AsyncResult.cs \
	../src/monad/monad/src/engine/hostifaces/ChoiceDescription.cs \
	../src/monad/monad/src/engine/hostifaces/Command.cs \
	../src/monad/monad/src/engine/hostifaces/Connection.cs \
	../src/monad/monad/src/engine/hostifaces/ConnectionBase.cs \
	../src/monad/monad/src/engine/hostifaces/ConnectionFactory.cs \
	../src/monad/monad/src/engine/hostifaces/DefaultHost.cs \
	../src/monad/monad/src/engine/hostifaces/FieldDescription.cs \
	../src/monad/monad/src/engine/hostifaces/History.cs \
	../src/monad/monad/src/engine/hostifaces/InformationalRecord.cs \
	../src/monad/monad/src/engine/hostifaces/InternalHost.cs \
	../src/monad/monad/src/engine/hostifaces/InternalHostRawUserInterface.cs \
	../src/monad/monad/src/engine/hostifaces/InternalHostUserInterface.cs \
	../src/monad/monad/src/engine/hostifaces/internalHostuserInterfacesecurity.cs \
	../src/monad/monad/src/engine/hostifaces/ListModifier.cs \
	../src/monad/monad/src/engine/hostifaces/LocalConnection.cs \
	../src/monad/monad/src/engine/hostifaces/LocalPipeline.cs \
	../src/monad/monad/src/engine/hostifaces/MshHost.cs \
	../src/monad/monad/src/engine/hostifaces/MshHostRawUserInterface.cs \
	../src/monad/monad/src/engine/hostifaces/MshHostUserInterface.cs \
	../src/monad/monad/src/engine/hostifaces/Parameter.cs \
	../src/monad/monad/src/engine/hostifaces/Pipeline.cs \
	../src/monad/monad/src/engine/hostifaces/pipelinebase.cs \
	../src/monad/monad/src/engine/hostifaces/PowerShell.cs \
	../src/monad/monad/src/engine/hostifaces/PSCommand.cs \
	../src/monad/monad/src/engine/hostifaces/PSDataCollection.cs \
	../src/monad/monad/src/engine/hostifaces/RunspaceInit.cs \
	../src/monad/monad/src/engine/hostifaces/RunspacePool.cs \
	../src/monad/monad/src/engine/hostifaces/RunspacePoolInternal.cs \
	../src/monad/monad/src/engine/hostifaces/PowerShellProcessInstance.cs \
	../src/monad/monad/src/engine/remoting/common/ObjectRef.cs \
	../src/monad/monad/src/engine/remoting/common/RunspacePoolStateInfo.cs \
	../src/monad/monad/src/engine/remoting/common/PSETWTracer.cs \
	../src/monad/monad/src/engine/remoting/client/remoterunspaceinfo.cs \
	../src/monad/monad/src/engine/remoting/host/RemoteHostMethodInfo.cs \
	../src/monad/monad/src/engine/remoting/client/remotepipeline.cs \
	../src/monad/monad/src/engine/remoting/client/remoterunspace.cs \
	../src/monad/monad/src/engine/remoting/client/clientremotesession.cs \
	../src/monad/monad/src/engine/remoting/client/Job.cs \
	../src/monad/monad/src/engine/remoting/client/Job2.cs \
	../src/monad/monad/src/engine/remoting/client/JobSourceAdapter.cs \
	../src/monad/monad/src/engine/remoting/client/PSProxyJob.cs \
	../src/monad/monad/src/engine/remoting/client/PowerShellStreams.cs \
	../src/monad/monad/src/engine/remoting/client/JobManager.cs \
	../src/monad/monad/src/engine/remoting/client/ThrottlingJob.cs \
	../src/monad/monad/src/engine/remoting/client/remotingprotocol.cs \
	../src/monad/monad/src/engine/remoting/client/clientremotesessionprotocolstatemachine.cs \
	../src/monad/monad/src/engine/remoting/client/remotingprotocolimplementation.cs \
	../src/monad/monad/src/engine/remoting/client/RemotingErrorRecord.cs \
	../src/monad/monad/src/engine/remoting/client/RemoteRunspacePoolInternal.cs \
	../src/monad/monad/src/engine/remoting/client/ClientRemotePowerShell.cs \
	../src/monad/monad/src/engine/remoting/client/RemotingProtocol2.cs \
	../src/monad/monad/src/engine/remoting/client/ClientMethodExecutor.cs \
	../src/monad/monad/src/engine/remoting/client/RunspaceRef.cs \
	../src/monad/monad/src/engine/remoting/common/PSSessionConfigurationTypeOption.cs \
	../src/monad/monad/src/engine/remoting/common/psstreamobject.cs \
	../src/monad/monad/src/engine/remoting/common/Indexer.cs \
	../src/monad/monad/src/engine/remoting/common/remotesession.cs \
	../src/monad/monad/src/engine/remoting/common/fragmentor.cs \
	../src/monad/monad/src/engine/remoting/common/misc.cs \
	../src/monad/monad/src/engine/remoting/common/remotingexceptions.cs \
	../src/monad/monad/src/engine/remoting/common/throttlemanager.cs \
	../src/monad/monad/src/engine/remoting/common/AsyncObject.cs \
	../src/monad/monad/src/engine/remoting/common/RunspaceConnectionInfo.cs \
	../src/monad/monad/src/engine/remoting/common/RunspaceInitInfo.cs \
	../src/monad/monad/src/engine/remoting/common/DispatchTable.cs \
	../src/monad/monad/src/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs \
	../src/monad/monad/src/engine/remoting/common/WireDataFormat/RemoteHost.cs \
	../src/monad/monad/src/engine/remoting/common/WireDataFormat/RemoteHostEncoder.cs \
	../src/monad/monad/src/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs \
	../src/monad/monad/src/engine/remoting/common/WireDataFormat/RemotingDataObject.cs \
	../src/monad/monad/src/engine/remoting/common/RemoteSessionNamedPipe.cs \
	../src/monad/monad/src/engine/remoting/server/OutOfProcServerMediator.cs \
	../src/monad/monad/src/engine/remoting/server/ServerMethodExecutor.cs \
	../src/monad/monad/src/engine/remoting/server/serverremotesession.cs \
	../src/monad/monad/src/engine/remoting/server/serverremotesessionstatemachine.cs \
	../src/monad/monad/src/engine/remoting/server/serverremotingprotocol.cs \
	../src/monad/monad/src/engine/remoting/server/ServerSteppablePipelineDriver.cs \
	../src/monad/monad/src/engine/remoting/server/ServerSteppablePipelineSubscriber.cs \
	../src/monad/monad/src/engine/remoting/server/serverremotingprotocolimplementation.cs \
	../src/monad/monad/src/engine/remoting/server/ServerRemoteHost.cs \
	../src/monad/monad/src/engine/remoting/server/ServerRemoteHostUserInterface.cs \
	../src/monad/monad/src/engine/remoting/server/ServerRemoteHostRawUserInterface.cs \
	../src/monad/monad/src/engine/remoting/server/ServerRunspacePoolDriver.cs \
	../src/monad/monad/src/engine/remoting/server/ServerPowerShellDriver.cs \
	../src/monad/monad/src/engine/remoting/server/ServerRemotingProtocol2.cs \
	../src/monad/monad/src/engine/remoting/server/WSManChannelEvents.cs \
	../src/monad/monad/src/engine/remoting/commands/CustomShellCommands.cs \
	../src/monad/monad/src/engine/remoting/commands/InvokeCommandCommand.cs \
	../src/monad/monad/src/engine/remoting/commands/newrunspacecommand.cs \
	../src/monad/monad/src/engine/remoting/commands/DisconnectPSSession.cs \
	../src/monad/monad/src/engine/remoting/commands/ConnectPSSession.cs \
	../src/monad/monad/src/engine/remoting/commands/ReceivePSSession.cs \
	../src/monad/monad/src/engine/remoting/commands/runspacerepository.cs \
	../src/monad/monad/src/engine/remoting/commands/getrunspacecommand.cs \
	../src/monad/monad/src/engine/remoting/commands/remotingcommandutil.cs \
	../src/monad/monad/src/engine/remoting/commands/removerunspacecommand.cs \
	../src/monad/monad/src/engine/remoting/commands/StartJob.cs \
	../src/monad/monad/src/engine/remoting/commands/JobRepository.cs \
	../src/monad/monad/src/engine/remoting/commands/PSRemotingCmdlet.cs \
	../src/monad/monad/src/engine/remoting/commands/GetJob.cs \
	../src/monad/monad/src/engine/remoting/commands/ReceiveJob.cs \
	../src/monad/monad/src/engine/remoting/commands/StopJob.cs \
	../src/monad/monad/src/engine/remoting/commands/WaitJob.cs \
	../src/monad/monad/src/engine/remoting/commands/RemoveJob.cs \
	../src/monad/monad/src/engine/remoting/commands/SuspendJob.cs \
	../src/monad/monad/src/engine/remoting/commands/ResumeJob.cs \
	../src/monad/monad/src/engine/remoting/commands/DebugJob.cs \
	../src/monad/monad/src/engine/remoting/commands/PushRunspaceCommand.cs \
	../src/monad/monad/src/engine/remoting/commands/PopRunspaceCommand.cs \
	../src/monad/monad/src/engine/remoting/commands/NewPSSessionOptionCommand.cs \
	../src/monad/monad/src/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs \
	../src/monad/monad/src/engine/remoting/commands/NewPSSessionConfigurationFile.cs \
	../src/monad/monad/src/engine/remoting/commands/TestPSSessionConfigurationFile.cs \
	../src/monad/monad/src/engine/remoting/commands/EnterPSHostProcessCommand.cs \
	../src/monad/monad/src/engine/remoting/fanin/PSPrincipal.cs \
	../src/monad/monad/src/engine/remoting/fanin/BaseTransportManager.cs \
	../src/monad/monad/src/engine/remoting/fanin/InitialSessionStateProvider.cs \
	../src/monad/monad/src/engine/remoting/fanin/PSSessionConfigurationData.cs \
	../src/monad/monad/src/engine/remoting/fanin/OutOfProcTransportManager.cs \
	../src/monad/monad/src/engine/remoting/fanin/PriorityCollection.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManTransportManager.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManNativeAPI.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManPlugin.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManPluginFacade.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManPluginShellSession.cs \
	../src/monad/monad/src/engine/remoting/fanin/WSManPluginTransportManager.cs \
	../src/monad/monad/src/logging/LogContext.cs \
	../src/monad/monad/src/logging/LogProvider.cs \
	../src/monad/monad/src/logging/MshLog.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfiguration.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationEntry.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationEntryCollection.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationTypeAttribute.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationAttributeException.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationTypeException.cs \
	../src/monad/monad/src/minishell/api/RunspaceConfigurationHelper.cs \
	../src/monad/monad/src/minishell/api/FormatAndTypeDataHelper.cs \
	../src/monad/monad/src/engine/Attributes.cs \
	../src/monad/monad/src/engine/CommandMetadata.cs \
	../src/monad/monad/src/engine/SerializationStrings.cs \
	../src/monad/monad/src/engine/SpecialVariables.cs \
	../src/monad/monad/src/engine/Utils.cs \
	../src/monad/monad/src/engine/regex.cs \
	../src/monad/monad/src/engine/serialization.cs \
	../src/monad/monad/src/engine/DataStoreAdapter.cs \
	../src/monad/monad/src/engine/DataStoreAdapterProvider.cs \
	../src/monad/monad/src/namespaces/ContainerProviderBase.cs \
	../src/monad/monad/src/namespaces/CoreCommandContext.cs \
	../src/monad/monad/src/namespaces/DriveProviderBase.cs \
	../src/monad/monad/src/namespaces/IContentProvider.cs \
	../src/monad/monad/src/namespaces/IContentReader.cs \
	../src/monad/monad/src/namespaces/IContentWriter.cs \
	../src/monad/monad/src/namespaces/IDynamicPropertyProvider.cs \
	../src/monad/monad/src/namespaces/IPermissionProvider.cs \
	../src/monad/monad/src/namespaces/IPropertiesProvider.cs \
	../src/monad/monad/src/namespaces/ItemProviderBase.cs \
	../src/monad/monad/src/namespaces/LocationGlobber.cs \
	../src/monad/monad/src/namespaces/NavigationProviderBase.cs \
	../src/monad/monad/src/namespaces/PathInfo.cs \
	../src/monad/monad/src/namespaces/ProviderBase.cs \
	../src/monad/monad/src/namespaces/ProviderBaseSecurity.cs \
	../src/monad/monad/src/namespaces/ProviderDeclarationAttribute.cs \
	../src/monad/monad/src/namespaces/StackInfo.cs \
	../src/monad/monad/src/namespaces/RegistryProvider.cs \
	../src/monad/monad/src/namespaces/RegistrySecurity.cs \
	../src/monad/monad/src/namespaces/RegistryWrapper.cs \
	../src/monad/monad/src/namespaces/Buffer.cs \
	../src/monad/monad/src/namespaces/SafeRegistryHandle.cs \
	../src/monad/monad/src/engine/lang/parserutils.cs \
	../src/monad/monad/src/engine/lang/scriptblock.cs \
	../src/monad/monad/src/engine/InternalCommands.cs \
	../src/monad/monad/src/engine/lang/codegen.cs \
	../src/monad/monad/src/engine/lang/interface/PSParser.cs \
	../src/monad/monad/src/engine/lang/interface/PSToken.cs \
	../src/monad/monad/src/engine/lang/interface/PSParseError.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameter.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameterAssociation.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatGroupManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Complex.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_List.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Table.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Wide.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatViewManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatXMLWriter.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommandParameters.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommand.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/format-default/format-default.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/ColumnWidthManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormattingObjectsDeserializer.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/OutputQueue.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/ListWriter.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/TableWriter.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormatMsgCtxManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/BaseOutputtingCommand.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/out-textInterface/OutTextInterface.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/FormattingObjects.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/ComplexWriter.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/ILineOutput.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/OutputManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/BaseCommand.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/out-console/ConsoleLineOutput.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/out-console/OutConsole.cs \
	../src/monad/monad/src/engine/parser/ast.cs \
	../src/monad/monad/src/engine/parser/AstVisitor.cs \
	../src/monad/monad/src/engine/parser/CharTraits.cs \
	../src/monad/monad/src/engine/parser/ConstantValues.cs \
	../src/monad/monad/src/engine/parser/Compiler.cs \
	../src/monad/monad/src/engine/parser/DebugViewWriter.cs \
	../src/monad/monad/src/engine/parser/Parser.cs \
	../src/monad/monad/src/engine/parser/Position.cs \
	../src/monad/monad/src/engine/parser/PreOrderVisitor.cs \
	../src/monad/monad/src/engine/parser/SafeValues.cs \
	../src/monad/monad/src/engine/parser/SemanticChecks.cs \
	../src/monad/monad/src/engine/parser/SymbolResolver.cs \
	../src/monad/monad/src/engine/parser/token.cs \
	../src/monad/monad/src/engine/parser/tokenizer.cs \
	../src/monad/monad/src/engine/parser/TypeResolver.cs \
	../src/monad/monad/src/engine/parser/VariableAnalysis.cs \
	../src/monad/monad/src/engine/runtime/CompiledScriptBlock.cs \
	../src/monad/monad/src/engine/runtime/ScriptBlockToPowerShell.cs \
	../src/monad/monad/src/engine/runtime/MutableTuple.cs \
	../src/monad/monad/src/engine/runtime/Binding/Binders.cs \
	../src/monad/monad/src/engine/runtime/Operations/ArrayOps.cs \
	../src/monad/monad/src/engine/runtime/Operations/ClassOps.cs \
	../src/monad/monad/src/engine/runtime/Operations/MiscOps.cs \
	../src/monad/monad/src/engine/runtime/Operations/NumericOps.cs \
	../src/monad/monad/src/engine/runtime/Operations/StringOps.cs \
	../src/monad/monad/src/engine/runtime/Operations/VariableOps.cs \
	../src/monad/monad/src/engine/parser/PSType.cs \
	../src/monad/monad/src/engine/interpreter/AddInstruction.cs \
	../src/monad/monad/src/engine/interpreter/ArrayOperations.cs \
	../src/monad/monad/src/engine/interpreter/BranchLabel.cs \
	../src/monad/monad/src/engine/interpreter/CallInstruction.cs \
	../src/monad/monad/src/engine/interpreter/CallInstruction.Generated.cs \
	../src/monad/monad/src/engine/interpreter/ControlFlowInstructions.cs \
	../src/monad/monad/src/engine/interpreter/DivInstruction.cs \
	../src/monad/monad/src/engine/interpreter/DynamicInstructionN.cs \
	../src/monad/monad/src/engine/interpreter/DynamicInstructions.Generated.cs \
	../src/monad/monad/src/engine/interpreter/DynamicSplatInstruction.cs \
	../src/monad/monad/src/engine/interpreter/EqualInstruction.cs \
	../src/monad/monad/src/engine/interpreter/FieldOperations.cs \
	../src/monad/monad/src/engine/interpreter/GreaterThanInstruction.cs \
	../src/monad/monad/src/engine/interpreter/ILightCallSiteBinder.cs \
	../src/monad/monad/src/engine/interpreter/Instruction.cs \
	../src/monad/monad/src/engine/interpreter/InstructionFactory.cs \
	../src/monad/monad/src/engine/interpreter/InstructionList.cs \
	../src/monad/monad/src/engine/interpreter/InterpretedFrame.cs \
	../src/monad/monad/src/engine/interpreter/Interpreter.cs \
	../src/monad/monad/src/engine/interpreter/LabelInfo.cs \
	../src/monad/monad/src/engine/interpreter/LessThanInstruction.cs \
	../src/monad/monad/src/engine/interpreter/LightCompiler.cs \
	../src/monad/monad/src/engine/interpreter/LightDelegateCreator.cs \
	../src/monad/monad/src/engine/interpreter/LightLambda.cs \
	../src/monad/monad/src/engine/interpreter/LightLambda.Generated.cs \
	../src/monad/monad/src/engine/interpreter/LightLambdaClosureVisitor.cs \
	../src/monad/monad/src/engine/interpreter/LocalAccess.cs \
	../src/monad/monad/src/engine/interpreter/LocalVariables.cs \
	../src/monad/monad/src/engine/interpreter/LoopCompiler.cs \
	../src/monad/monad/src/engine/interpreter/MulInstruction.cs \
	../src/monad/monad/src/engine/interpreter/NotEqualInstruction.cs \
	../src/monad/monad/src/engine/interpreter/NumericConvertInstruction.cs \
	../src/monad/monad/src/engine/interpreter/PowerShellInstructions.cs \
	../src/monad/monad/src/engine/interpreter/RuntimeVariables.cs \
	../src/monad/monad/src/engine/interpreter/StackOperations.cs \
	../src/monad/monad/src/engine/interpreter/SubInstruction.cs \
	../src/monad/monad/src/engine/interpreter/TypeOperations.cs \
	../src/monad/monad/src/engine/interpreter/Utilities.cs \
	../src/monad/monad/src/engine/AutomationNull.cs \
	../src/monad/monad/src/engine/Pipe.cs \
	../src/monad/monad/src/engine/pipeline.cs \
	../src/monad/monad/src/namespaces/AliasProvider.cs \
	../src/monad/monad/src/namespaces/EnvironmentProvider.cs \
	../src/monad/monad/src/namespaces/FileSystemContentStream.cs \
	../src/monad/monad/src/namespaces/FileSystemProvider.cs \
	../src/monad/monad/src/namespaces/FileSystemSecurity.cs \
	../src/monad/monad/src/namespaces/FunctionProvider.cs \
	../src/monad/monad/src/namespaces/SessionStateProviderBase.cs \
	../src/monad/monad/src/namespaces/VariableProvider.cs \
	../src/monad/monad/src/namespaces/Win32Native.cs \
	../src/monad/monad/src/engine/Credential.cs \
	../src/monad/monad/src/engine/MshSecurityException.cs \
	../src/monad/monad/src/security/nativeMethods.cs \
	../src/monad/monad/src/security/Authenticode.cs \
	../src/monad/monad/src/engine/SecurityDescriptorCmdletProviderInterfaces.cs \
	../src/monad/monad/src/engine/SessionStateSecurityDescriptorInterface.cs \
	../src/monad/monad/src/engine/SecurityManagerBase.cs \
	../src/monad/monad/src/security/SecurityManager.cs \
	../src/monad/monad/src/security/CredentialParameter.cs \
	../src/monad/monad/src/security/MshSignature.cs \
	../src/monad/monad/src/security/SecuritySupport.cs \
	../src/monad/monad/src/engine/ArgumentTypeConverterAttribute.cs \
	../src/monad/monad/src/engine/DriveNames.cs \
	../src/monad/monad/src/engine/ProviderNames.cs \
	../src/monad/monad/src/engine/ScopedItemSearcher.cs \
	../src/monad/monad/src/engine/InitialSessionState.cs \
	../src/monad/monad/src/engine/SessionState.cs \
	../src/monad/monad/src/engine/SessionStateAliasAPIs.cs \
	../src/monad/monad/src/engine/SessionStateCmdletAPIs.cs \
	../src/monad/monad/src/engine/SessionStateContainer.cs \
	../src/monad/monad/src/engine/SessionStateContent.cs \
	../src/monad/monad/src/engine/SessionStateDriveAPIs.cs \
	../src/monad/monad/src/engine/SessionStateDynamicProperty.cs \
	../src/monad/monad/src/engine/SessionStateFunctionAPIs.cs \
	../src/monad/monad/src/engine/SessionStateItem.cs \
	../src/monad/monad/src/engine/SessionStateLocationAPIs.cs \
	../src/monad/monad/src/engine/SessionStateNavigation.cs \
	../src/monad/monad/src/engine/SessionStateProperty.cs \
	../src/monad/monad/src/engine/SessionStateProviderAPIs.cs \
	../src/monad/monad/src/engine/SessionStateScopeAPIs.cs \
	../src/monad/monad/src/engine/SessionStateVariableAPIs.cs \
	../src/monad/monad/src/engine/SessionStateCapacityVariable.cs \
	../src/monad/monad/src/engine/QuestionMarkVariable.cs \
	../src/monad/monad/src/engine/CultureVariable.cs \
	../src/monad/monad/src/engine/SessionStateScope.cs \
	../src/monad/monad/src/engine/SessionStateScopeEnumerator.cs \
	../src/monad/monad/src/engine/SessionStateStrings.cs \
	../src/monad/monad/src/engine/SessionStateUtils.cs \
	../src/monad/monad/src/engine/ShellVariable.cs \
	../src/monad/monad/src/engine/VariableAttributeCollection.cs \
	../src/monad/monad/src/engine/VariablePath.cs \
	../src/monad/monad/src/singleshell/config/MshSnapinInfo.cs \
	../src/monad/monad/src/singleshell/config/RunspaceConfigForSingleShell.cs \
	../src/monad/monad/src/singleshell/config/MshConsoleInfo.cs \
	../src/monad/monad/src/singleshell/config/MshConsoleLoadException.cs \
	../src/monad/monad/src/singleshell/config/MshSnapinLoadException.cs \
	../src/monad/monad/src/CoreCLR/CorePsExtensions.cs \
	../src/monad/monad/src/CoreCLR/CorePsStub.cs \
	../src/monad/monad/src/utils/ArchitectureSensitiveAttribute.cs \
	../src/monad/monad/src/utils/assert.cs \
	../src/monad/monad/src/utils/CommandDiscoveryExceptions.cs \
	../src/monad/monad/src/utils/CommandProcessorExceptions.cs \
	../src/monad/monad/src/utils/CoreProviderCmdlets.cs \
	../src/monad/monad/src/utils/ExecutionExceptions.cs \
	../src/monad/monad/src/utils/ExtensionMethods.cs \
	../src/monad/monad/src/utils/HostInterfacesExceptions.cs \
	../src/monad/monad/src/utils/IObjectReader.cs \
	../src/monad/monad/src/utils/IObjectWriter.cs \
	../src/monad/monad/src/utils/MetadataExceptions.cs \
	../src/monad/monad/src/utils/MshArgumentException.cs \
	../src/monad/monad/src/utils/MshArgumentNullException.cs \
	../src/monad/monad/src/utils/MshArgumentOutOfRangeException.cs \
	../src/monad/monad/src/utils/MshInvalidOperationException.cs \
	../src/monad/monad/src/utils/MshNotImplementedException.cs \
	../src/monad/monad/src/utils/MshNotSupportedException.cs \
	../src/monad/monad/src/utils/MshObjectDisposedException.cs \
	../src/monad/monad/src/utils/MshTraceSource.cs \
	../src/monad/monad/src/utils/ObjectReader.cs \
	../src/monad/monad/src/utils/ObjectStream.cs \
	../src/monad/monad/src/utils/ObjectWriter.cs \
	../src/monad/monad/src/utils/ParameterBinderExceptions.cs \
	../src/monad/monad/src/utils/ParserException.cs \
	../src/monad/monad/src/utils/PathUtils.cs \
	../src/monad/monad/src/utils/PsUtils.cs \
	../src/monad/monad/src/utils/ResourceManagerCache.cs \
	../src/monad/monad/src/utils/RuntimeException.cs \
	../src/monad/monad/src/utils/SessionStateExceptions.cs \
	../src/monad/monad/src/utils/StringUtil.cs \
	../src/monad/monad/src/utils/StructuredTraceSource.cs \
	../src/monad/monad/src/utils/Verbs.cs \
	../src/monad/monad/src/utils/CryptoUtils.cs \
	../src/monad/monad/src/utils/PInvokeDllNames.cs \
	../src/monad/monad/src/utils/PlatformInvokes.cs \
	../src/monad/monad/src/utils/ClrFacade.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshObjectUtil.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/Utilities/Mshexpression.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/commands.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionDataMethods.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Misc.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Table.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/FormatTable.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Complex.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_List.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Table.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Views.cs \
	../src/monad/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Wide.cs \
	../src/monad/monad/src/engine/CommandCompletion/PseudoParameterBinder.cs \
	../src/monad/monad/src/engine/CommandCompletion/CommandCompletion.cs \
	../src/monad/monad/src/engine/CommandCompletion/CompletionAnalysis.cs \
	../src/monad/monad/src/engine/CommandCompletion/CompletionCompleters.cs \
	../src/monad/monad/src/engine/CommandCompletion/CompletionExecutionHelper.cs \
	../src/monad/monad/src/engine/CommandCompletion/CompletionResult.cs \
	../src/monad/monad/src/cimSupport/cmdletization/MethodInvocationInfo.cs \
	../src/monad/monad/src/cimSupport/cmdletization/MethodParameter.cs \
	../src/monad/monad/src/cimSupport/cmdletization/MethodParametersCollection.cs \
	../src/monad/monad/src/cimSupport/cmdletization/QueryBuilder.cs \
	../src/monad/monad/src/cimSupport/cmdletization/ObjectModelWrapper.cs \
	../src/monad/monad/src/cimSupport/cmdletization/EnumWriter.cs \
	../src/monad/monad/src/cimSupport/cmdletization/ScriptWriter.cs \
	../src/monad/monad/src/cimSupport/cmdletization/cim/WildcardPatternToCimQueryParser.cs \
	../src/monad/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.objectModel.autogen.cs \
	../src/monad/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.xmlSerializer.autogen.cs \
	../src/monad/monad/src/cimSupport/other/ciminstancetypeadapter.cs
