# This is an automatically generated file for the make dependency: SYS_AUTO

SYS_AUTO_SRCS_WIN=\
	../../../jws/pswin/admin/monad/src/engine/ChildrenCmdletProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/CmdletFamilyProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshCmdlet.cs	\
	../../../jws/pswin/admin/monad/src/engine/cmdlet.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandFactory.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandParameter.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandProcessor.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandProcessorBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommonCommandParameters.cs	\
	../../../jws/pswin/admin/monad/src/engine/ContentCmdletProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/DriveInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/EnumExpressionEvaluator.cs	\
	../../../jws/pswin/admin/monad/src/engine/EnumMinimumDisambiguation.cs	\
	../../../jws/pswin/admin/monad/src/engine/ErrorPackage.cs	\
	../../../jws/pswin/admin/monad/src/engine/InvocationInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/ItemCmdletProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/NativeCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/PathInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/ProgressRecord.cs	\
	../../../jws/pswin/admin/monad/src/engine/InformationRecord.cs	\
	../../../jws/pswin/admin/monad/src/engine/PropertyCmdletProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/ProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/ProxyCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStatePublic.cs	\
	../../../jws/pswin/admin/monad/src/engine/ScriptCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/ScriptCommandProcessor.cs	\
	../../../jws/pswin/admin/monad/src/engine/UserFeedbackParameters.cs	\
	../../../jws/pswin/admin/monad/src/engine/VariableInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/ICommandRuntime.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshCommandRuntime.cs	\
	../../../jws/pswin/admin/monad/src/engine/DefaultCommandRuntime.cs	\
	../../../jws/pswin/admin/monad/src/engine/AliasInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/ApplicationInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/CmdletInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/CmdletParameterBinderController.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandDiscovery.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandPathSearch.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandSearcher.cs	\
	../../../jws/pswin/admin/monad/src/engine/CompiledCommandParameter.cs	\
	../../../jws/pswin/admin/monad/src/engine/ExternalScriptInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/FilterInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/FunctionInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/ConfigurationInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/DscResourceInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/GetCommandCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/MergedCommandParameterMetadata.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterBinderBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterBinderController.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterSetInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterSetPromptingData.cs	\
	../../../jws/pswin/admin/monad/src/engine/ParameterSetSpecificMetadata.cs	\
	../../../jws/pswin/admin/monad/src/engine/PositionalCommandParameter.cs	\
	../../../jws/pswin/admin/monad/src/engine/PseudoParameterBinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/PseudoParameters.cs	\
	../../../jws/pswin/admin/monad/src/engine/ReflectionParameterBinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/ScriptInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/scriptparameterbinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/scriptparameterbindercontroller.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshSnapinQualifiedName.cs	\
	../../../jws/pswin/admin/monad/src/engine/TypeMetadata.cs	\
	../../../jws/pswin/admin/monad/src/engine/WorkflowInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/MinishellParameterBinderController.cs	\
	../../../jws/pswin/admin/monad/src/engine/NativeCommandParameterBinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/NativeCommandParameterBinderController.cs	\
	../../../jws/pswin/admin/monad/src/engine/NativeCommandProcessor.cs	\
	../../../jws/pswin/admin/monad/src/engine/DscResourceSearcher.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/AnalysisCache.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ExportModuleMemberCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/GetModuleCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ImportModuleCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ModuleCmdletBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ModuleIntrinsics.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ModuleSpecification.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ModuleUtils.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/NewModuleCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/NewModuleManifestCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/PSModuleInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/RemoteDiscoveryHelper.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/RemoveModuleCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/ScriptAnalysis.cs	\
	../../../jws/pswin/admin/monad/src/engine/Modules/TestModuleManifestCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/AutomationEngine.cs	\
	../../../jws/pswin/admin/monad/src/engine/EngineIntrinsics.cs	\
	../../../jws/pswin/admin/monad/src/engine/ExecutionContext.cs	\
	../../../jws/pswin/admin/monad/src/engine/PSVersionInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/EventManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/ObjectEventRegistrationBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/debugger/Breakpoint.cs	\
	../../../jws/pswin/admin/monad/src/engine/debugger/debugger.cs	\
	../../../jws/pswin/admin/monad/src/engine/CoreAdapter.cs	\
	../../../jws/pswin/admin/monad/src/engine/ThirdPartyAdapter.cs	\
	../../../jws/pswin/admin/monad/src/engine/LanguagePrimitives.cs	\
	../../../jws/pswin/admin/monad/src/engine/NullString.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshMemberInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshObject.cs	\
	../../../jws/pswin/admin/monad/src/engine/TypeTable.cs	\
	../../../jws/pswin/admin/monad/src/engine/ExtendedTypeSystemException.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshReference.cs	\
	../../../jws/pswin/admin/monad/src/engine/WinRT/IInspectable.cs	\
	../../../jws/pswin/admin/monad/src/help/CabinetAPI.cs	\
	../../../jws/pswin/admin/monad/src/help/CabinetNativeApi.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/AsyncResult.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/ChoiceDescription.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/Command.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/Connection.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/ConnectionBase.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/ConnectionFactory.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/DefaultHost.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/FieldDescription.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/History.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/InformationalRecord.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/InternalHost.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/InternalHostRawUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/InternalHostUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/internalHostuserInterfacesecurity.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/ListModifier.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/LocalConnection.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/LocalPipeline.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/MshHost.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/MshHostRawUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/MshHostUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/Parameter.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/Pipeline.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/pipelinebase.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/PowerShell.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/PSCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/PSDataCollection.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/RunspaceInit.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/RunspacePool.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/RunspacePoolInternal.cs	\
	../../../jws/pswin/admin/monad/src/engine/hostifaces/PowerShellProcessInstance.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/ObjectRef.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/RunspacePoolStateInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/PSETWTracer.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/remoterunspaceinfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/host/RemoteHostMethodInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/remotepipeline.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/remoterunspace.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/clientremotesession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/Job.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/Job2.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/JobSourceAdapter.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/PSProxyJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/PowerShellStreams.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/JobManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/ThrottlingJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/remotingprotocol.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/clientremotesessionprotocolstatemachine.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/remotingprotocolimplementation.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/RemotingErrorRecord.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/RemoteRunspacePoolInternal.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/ClientRemotePowerShell.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/RemotingProtocol2.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/ClientMethodExecutor.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/client/RunspaceRef.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/PSSessionConfigurationTypeOption.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/psstreamobject.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/Indexer.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/remotesession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/fragmentor.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/misc.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/remotingexceptions.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/throttlemanager.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/AsyncObject.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/RunspaceConnectionInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/RunspaceInitInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/DispatchTable.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/WireDataFormat/RemoteHost.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/WireDataFormat/RemoteHostEncoder.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/WireDataFormat/RemotingDataObject.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/common/RemoteSessionNamedPipe.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/OutOfProcServerMediator.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerMethodExecutor.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/serverremotesession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/serverremotesessionstatemachine.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/serverremotingprotocol.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerSteppablePipelineDriver.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerSteppablePipelineSubscriber.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/serverremotingprotocolimplementation.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerRemoteHost.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerRemoteHostUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerRemoteHostRawUserInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerRunspacePoolDriver.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerPowerShellDriver.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/ServerRemotingProtocol2.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/server/WSManChannelEvents.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/CustomShellCommands.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/InvokeCommandCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/newrunspacecommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/DisconnectPSSession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/ConnectPSSession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/ReceivePSSession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/runspacerepository.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/getrunspacecommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/remotingcommandutil.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/removerunspacecommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/StartJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/JobRepository.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/PSRemotingCmdlet.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/GetJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/ReceiveJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/StopJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/WaitJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/RemoveJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/SuspendJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/ResumeJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/DebugJob.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/PushRunspaceCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/PopRunspaceCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/NewPSSessionOptionCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/NewPSSessionConfigurationFile.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/TestPSSessionConfigurationFile.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/commands/EnterPSHostProcessCommand.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/PSPrincipal.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/BaseTransportManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/InitialSessionStateProvider.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/PSSessionConfigurationData.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/OutOfProcTransportManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/PriorityCollection.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManTransportManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManNativeAPI.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManPlugin.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManPluginFacade.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManPluginShellSession.cs	\
	../../../jws/pswin/admin/monad/src/engine/remoting/fanin/WSManPluginTransportManager.cs	\
	../../../jws/pswin/admin/monad/src/logging/LogContext.cs	\
	../../../jws/pswin/admin/monad/src/logging/LogProvider.cs	\
	../../../jws/pswin/admin/monad/src/logging/MshLog.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfiguration.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationEntry.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationEntryCollection.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationTypeAttribute.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationAttributeException.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationTypeException.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/RunspaceConfigurationHelper.cs	\
	../../../jws/pswin/admin/monad/src/minishell/api/FormatAndTypeDataHelper.cs	\
	../../../jws/pswin/admin/monad/src/engine/Attributes.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandMetadata.cs	\
	../../../jws/pswin/admin/monad/src/engine/SerializationStrings.cs	\
	../../../jws/pswin/admin/monad/src/engine/SpecialVariables.cs	\
	../../../jws/pswin/admin/monad/src/engine/Utils.cs	\
	../../../jws/pswin/admin/monad/src/engine/regex.cs	\
	../../../jws/pswin/admin/monad/src/engine/serialization.cs	\
	../../../jws/pswin/admin/monad/src/engine/DataStoreAdapter.cs	\
	../../../jws/pswin/admin/monad/src/engine/DataStoreAdapterProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/ContainerProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/CoreCommandContext.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/DriveProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IContentProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IContentReader.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IContentWriter.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IDynamicPropertyProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IPermissionProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/IPropertiesProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/ItemProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/LocationGlobber.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/NavigationProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/PathInfo.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/ProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/ProviderBaseSecurity.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/ProviderDeclarationAttribute.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/StackInfo.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/RegistryProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/RegistrySecurity.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/RegistryWrapper.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/Buffer.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/SafeRegistryHandle.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/parserutils.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/scriptblock.cs	\
	../../../jws/pswin/admin/monad/src/engine/InternalCommands.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/codegen.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/interface/PSParser.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/interface/PSToken.cs	\
	../../../jws/pswin/admin/monad/src/engine/lang/interface/PSParseError.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameter.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameterAssociation.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatGroupManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Complex.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_List.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Table.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Wide.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatViewManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatXMLWriter.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommandParameters.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommand.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/format-default/format-default.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/ColumnWidthManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormattingObjectsDeserializer.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/OutputQueue.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/ListWriter.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/TableWriter.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormatMsgCtxManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/BaseOutputtingCommand.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/out-textInterface/OutTextInterface.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/FormattingObjects.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/ComplexWriter.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/ILineOutput.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/OutputManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/BaseCommand.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/out-console/ConsoleLineOutput.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/out-console/OutConsole.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/ast.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/AstVisitor.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/CharTraits.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/ConstantValues.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/Compiler.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/DebugViewWriter.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/Parser.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/Position.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/PreOrderVisitor.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/SafeValues.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/SemanticChecks.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/SymbolResolver.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/token.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/tokenizer.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/TypeResolver.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/VariableAnalysis.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/CompiledScriptBlock.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/ScriptBlockToPowerShell.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/MutableTuple.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Binding/Binders.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/ArrayOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/ClassOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/MiscOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/NumericOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/StringOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/runtime/Operations/VariableOps.cs	\
	../../../jws/pswin/admin/monad/src/engine/parser/PSType.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/AddInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/ArrayOperations.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/BranchLabel.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/CallInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/CallInstruction.Generated.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/ControlFlowInstructions.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/DivInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/DynamicInstructionN.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/DynamicInstructions.Generated.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/DynamicSplatInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/EqualInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/FieldOperations.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/GreaterThanInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/ILightCallSiteBinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/Instruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/InstructionFactory.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/InstructionList.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/InterpretedFrame.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/Interpreter.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LabelInfo.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LessThanInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LightCompiler.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LightDelegateCreator.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LightLambda.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LightLambda.Generated.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LightLambdaClosureVisitor.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LocalAccess.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LocalVariables.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/LoopCompiler.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/MulInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/NotEqualInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/NumericConvertInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/PowerShellInstructions.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/RuntimeVariables.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/StackOperations.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/SubInstruction.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/TypeOperations.cs	\
	../../../jws/pswin/admin/monad/src/engine/interpreter/Utilities.cs	\
	../../../jws/pswin/admin/monad/src/engine/AutomationNull.cs	\
	../../../jws/pswin/admin/monad/src/engine/Pipe.cs	\
	../../../jws/pswin/admin/monad/src/engine/pipeline.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/AliasProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/EnvironmentProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/FileSystemContentStream.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/FileSystemProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/FileSystemSecurity.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/FunctionProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/SessionStateProviderBase.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/VariableProvider.cs	\
	../../../jws/pswin/admin/monad/src/namespaces/Win32Native.cs	\
	../../../jws/pswin/admin/monad/src/engine/Credential.cs	\
	../../../jws/pswin/admin/monad/src/engine/MshSecurityException.cs	\
	../../../jws/pswin/admin/monad/src/security/nativeMethods.cs	\
	../../../jws/pswin/admin/monad/src/security/Authenticode.cs	\
	../../../jws/pswin/admin/monad/src/engine/SecurityDescriptorCmdletProviderInterfaces.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateSecurityDescriptorInterface.cs	\
	../../../jws/pswin/admin/monad/src/engine/SecurityManagerBase.cs	\
	../../../jws/pswin/admin/monad/src/security/CredentialParameter.cs	\
	../../../jws/pswin/admin/monad/src/security/MshSignature.cs	\
	../../../jws/pswin/admin/monad/src/security/SecuritySupport.cs	\
	../../../jws/pswin/admin/monad/src/security/SecurityManager.cs	\
	../../../jws/pswin/admin/monad/src/engine/ArgumentTypeConverterAttribute.cs	\
	../../../jws/pswin/admin/monad/src/engine/DriveNames.cs	\
	../../../jws/pswin/admin/monad/src/engine/ProviderNames.cs	\
	../../../jws/pswin/admin/monad/src/engine/ScopedItemSearcher.cs	\
	../../../jws/pswin/admin/monad/src/engine/InitialSessionState.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionState.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateAliasAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateCmdletAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateContainer.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateContent.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateDriveAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateDynamicProperty.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateFunctionAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateItem.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateLocationAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateNavigation.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateProperty.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateProviderAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateScopeAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateVariableAPIs.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateCapacityVariable.cs	\
	../../../jws/pswin/admin/monad/src/engine/QuestionMarkVariable.cs	\
	../../../jws/pswin/admin/monad/src/engine/CultureVariable.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateScope.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateScopeEnumerator.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateStrings.cs	\
	../../../jws/pswin/admin/monad/src/engine/SessionStateUtils.cs	\
	../../../jws/pswin/admin/monad/src/engine/ShellVariable.cs	\
	../../../jws/pswin/admin/monad/src/engine/VariableAttributeCollection.cs	\
	../../../jws/pswin/admin/monad/src/engine/VariablePath.cs	\
	../../../jws/pswin/admin/monad/src/singleshell/config/MshSnapinInfo.cs	\
	../../../jws/pswin/admin/monad/src/singleshell/config/RunspaceConfigForSingleShell.cs	\
	../../../jws/pswin/admin/monad/src/singleshell/config/MshConsoleInfo.cs	\
	../../../jws/pswin/admin/monad/src/singleshell/config/MshConsoleLoadException.cs	\
	../../../jws/pswin/admin/monad/src/singleshell/config/MshSnapinLoadException.cs	\
	../../../jws/pswin/admin/monad/src/CoreCLR/CorePsExtensions.cs	\
	../../../jws/pswin/admin/monad/src/CoreCLR/CorePsStub.cs	\
	../../../jws/pswin/admin/monad/src/utils/ArchitectureSensitiveAttribute.cs	\
	../../../jws/pswin/admin/monad/src/utils/assert.cs	\
	../../../jws/pswin/admin/monad/src/utils/CommandDiscoveryExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/CommandProcessorExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/CoreProviderCmdlets.cs	\
	../../../jws/pswin/admin/monad/src/utils/ExecutionExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/ExtensionMethods.cs	\
	../../../jws/pswin/admin/monad/src/utils/HostInterfacesExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/IObjectReader.cs	\
	../../../jws/pswin/admin/monad/src/utils/IObjectWriter.cs	\
	../../../jws/pswin/admin/monad/src/utils/MetadataExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshArgumentException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshArgumentNullException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshArgumentOutOfRangeException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshInvalidOperationException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshNotImplementedException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshNotSupportedException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshObjectDisposedException.cs	\
	../../../jws/pswin/admin/monad/src/utils/MshTraceSource.cs	\
	../../../jws/pswin/admin/monad/src/utils/ObjectReader.cs	\
	../../../jws/pswin/admin/monad/src/utils/ObjectStream.cs	\
	../../../jws/pswin/admin/monad/src/utils/ObjectWriter.cs	\
	../../../jws/pswin/admin/monad/src/utils/ParameterBinderExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/ParserException.cs	\
	../../../jws/pswin/admin/monad/src/utils/PathUtils.cs	\
	../../../jws/pswin/admin/monad/src/utils/PsUtils.cs	\
	../../../jws/pswin/admin/monad/src/utils/ResourceManagerCache.cs	\
	../../../jws/pswin/admin/monad/src/utils/RuntimeException.cs	\
	../../../jws/pswin/admin/monad/src/utils/SessionStateExceptions.cs	\
	../../../jws/pswin/admin/monad/src/utils/StringUtil.cs	\
	../../../jws/pswin/admin/monad/src/utils/StructuredTraceSource.cs	\
	../../../jws/pswin/admin/monad/src/utils/Verbs.cs	\
	../../../jws/pswin/admin/monad/src/utils/CryptoUtils.cs	\
	../../../jws/pswin/admin/monad/src/utils/PInvokeDllNames.cs	\
	../../../jws/pswin/admin/monad/src/utils/PlatformInvokes.cs	\
	../../../jws/pswin/admin/monad/src/utils/ClrFacade.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshObjectUtil.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/Utilities/Mshexpression.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/commands.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionDataMethods.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Misc.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Table.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/FormatTable.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Complex.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_List.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Table.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Views.cs	\
	../../../jws/pswin/admin/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Wide.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/PseudoParameterBinder.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/CommandCompletion.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/CompletionAnalysis.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/CompletionCompleters.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/CompletionExecutionHelper.cs	\
	../../../jws/pswin/admin/monad/src/engine/CommandCompletion/CompletionResult.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/MethodInvocationInfo.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/MethodParameter.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/MethodParametersCollection.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/QueryBuilder.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/ObjectModelWrapper.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/EnumWriter.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/ScriptWriter.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/cim/WildcardPatternToCimQueryParser.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.objectModel.autogen.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.xmlSerializer.autogen.cs	\
	../../../jws/pswin/admin/monad/src/cimSupport/other/ciminstancetypeadapter.cs	\


SYS_AUTO_SRCS=\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ChildrenCmdletProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CmdletFamilyProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshCmdlet.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/cmdlet.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandFactory.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandProcessor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandProcessorBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommonCommandParameters.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ContentCmdletProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DriveInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/EnumExpressionEvaluator.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/EnumMinimumDisambiguation.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ErrorPackage.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/InvocationInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ItemCmdletProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/NativeCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PathInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ProgressRecord.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/InformationRecord.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PropertyCmdletProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ProxyCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStatePublic.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ScriptCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ScriptCommandProcessor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/UserFeedbackParameters.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/VariableInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ICommandRuntime.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshCommandRuntime.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DefaultCommandRuntime.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/AliasInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ApplicationInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CmdletInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CmdletParameterBinderController.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandDiscovery.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandPathSearch.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandSearcher.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CompiledCommandParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ExternalScriptInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/FilterInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/FunctionInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ConfigurationInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DscResourceInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/GetCommandCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MergedCommandParameterMetadata.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterBinderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterBinderController.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterSetInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterSetPromptingData.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ParameterSetSpecificMetadata.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PositionalCommandParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PseudoParameterBinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PseudoParameters.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ReflectionParameterBinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ScriptInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/scriptparameterbinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/scriptparameterbindercontroller.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshSnapinQualifiedName.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/TypeMetadata.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/WorkflowInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MinishellParameterBinderController.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/NativeCommandParameterBinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/NativeCommandParameterBinderController.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/NativeCommandProcessor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DscResourceSearcher.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/AnalysisCache.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ExportModuleMemberCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/GetModuleCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ImportModuleCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ModuleCmdletBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ModuleIntrinsics.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ModuleSpecification.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ModuleUtils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/NewModuleCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/NewModuleManifestCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/PSModuleInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/RemoteDiscoveryHelper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/RemoveModuleCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/ScriptAnalysis.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Modules/TestModuleManifestCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/AutomationEngine.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/EngineIntrinsics.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ExecutionContext.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/PSVersionInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/EventManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ObjectEventRegistrationBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/debugger/Breakpoint.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/debugger/debugger.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CoreAdapter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ThirdPartyAdapter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/LanguagePrimitives.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/NullString.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshMemberInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshObject.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/TypeTable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ExtendedTypeSystemException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshReference.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/WinRT/IInspectable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/help/CabinetAPI.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/help/CabinetNativeApi.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/AsyncResult.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/ChoiceDescription.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/Command.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/Connection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/ConnectionBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/ConnectionFactory.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/DefaultHost.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/FieldDescription.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/History.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/InformationalRecord.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/InternalHost.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/InternalHostRawUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/InternalHostUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/internalHostuserInterfacesecurity.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/ListModifier.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/LocalConnection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/LocalPipeline.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/MshHost.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/MshHostRawUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/MshHostUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/Parameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/Pipeline.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/pipelinebase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/PowerShell.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/PSCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/PSDataCollection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/RunspaceInit.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/RunspacePool.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/RunspacePoolInternal.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/hostifaces/PowerShellProcessInstance.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/ObjectRef.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/RunspacePoolStateInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/PSETWTracer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/remoterunspaceinfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/host/RemoteHostMethodInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/remotepipeline.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/remoterunspace.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/clientremotesession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/Job.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/Job2.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/JobSourceAdapter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/PSProxyJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/PowerShellStreams.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/JobManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/ThrottlingJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/remotingprotocol.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/clientremotesessionprotocolstatemachine.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/remotingprotocolimplementation.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/RemotingErrorRecord.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/RemoteRunspacePoolInternal.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/ClientRemotePowerShell.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/RemotingProtocol2.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/ClientMethodExecutor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/client/RunspaceRef.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/PSSessionConfigurationTypeOption.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/psstreamobject.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/Indexer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/remotesession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/fragmentor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/misc.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/remotingexceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/throttlemanager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/AsyncObject.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/RunspaceConnectionInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/RunspaceInitInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/DispatchTable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/WireDataFormat/EncodeAndDecode.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/WireDataFormat/RemoteHost.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/WireDataFormat/RemoteHostEncoder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/WireDataFormat/RemoteSessionCapability.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/WireDataFormat/RemotingDataObject.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/common/RemoteSessionNamedPipe.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/OutOfProcServerMediator.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerMethodExecutor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/serverremotesession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/serverremotesessionstatemachine.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/serverremotingprotocol.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerSteppablePipelineDriver.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerSteppablePipelineSubscriber.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/serverremotingprotocolimplementation.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerRemoteHost.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerRemoteHostUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerRemoteHostRawUserInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerRunspacePoolDriver.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerPowerShellDriver.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/ServerRemotingProtocol2.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/server/WSManChannelEvents.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/CustomShellCommands.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/InvokeCommandCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/newrunspacecommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/DisconnectPSSession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/ConnectPSSession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/ReceivePSSession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/runspacerepository.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/getrunspacecommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/remotingcommandutil.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/removerunspacecommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/StartJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/JobRepository.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/PSRemotingCmdlet.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/GetJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/ReceiveJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/StopJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/WaitJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/RemoveJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/SuspendJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/ResumeJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/DebugJob.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/PushRunspaceCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/PopRunspaceCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/NewPSSessionOptionCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/NewPSSessionConfigurationOptionCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/NewPSSessionConfigurationFile.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/TestPSSessionConfigurationFile.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/commands/EnterPSHostProcessCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/PSPrincipal.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/BaseTransportManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/InitialSessionStateProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/PSSessionConfigurationData.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/OutOfProcTransportManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/PriorityCollection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManTransportManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManNativeAPI.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManPlugin.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManPluginFacade.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManPluginShellSession.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/remoting/fanin/WSManPluginTransportManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/logging/LogContext.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/logging/LogProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/logging/MshLog.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfiguration.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationEntry.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationEntryCollection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationTypeAttribute.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationAttributeException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationTypeException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/RunspaceConfigurationHelper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/minishell/api/FormatAndTypeDataHelper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Attributes.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandMetadata.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SerializationStrings.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SpecialVariables.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Utils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/regex.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/serialization.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DataStoreAdapter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DataStoreAdapterProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/ContainerProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/CoreCommandContext.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/DriveProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IContentProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IContentReader.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IContentWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IDynamicPropertyProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IPermissionProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/IPropertiesProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/ItemProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/LocationGlobber.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/NavigationProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/PathInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/ProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/ProviderBaseSecurity.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/ProviderDeclarationAttribute.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/StackInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/RegistryProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/RegistrySecurity.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/RegistryWrapper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/Buffer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/SafeRegistryHandle.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/parserutils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/scriptblock.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/InternalCommands.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/codegen.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/interface/PSParser.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/interface/PSToken.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/lang/interface/PSParseError.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshParameterAssociation.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatGroupManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Complex.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_List.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Table.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewGenerator_Wide.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatViewManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatXMLWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommandParameters.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/BaseFormattingCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/format-default/format-default.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/ColumnWidthManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormattingObjectsDeserializer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/OutputQueue.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/ListWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/TableWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormatMsgCtxManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/BaseOutputtingCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/out-textInterface/OutTextInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/FormattingObjects.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/ComplexWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/ILineOutput.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/OutputManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/BaseCommand.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/out-console/ConsoleLineOutput.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/out-console/OutConsole.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/ast.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/AstVisitor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/CharTraits.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/ConstantValues.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/Compiler.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/DebugViewWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/Parser.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/Position.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/PreOrderVisitor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/SafeValues.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/SemanticChecks.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/SymbolResolver.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/token.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/tokenizer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/TypeResolver.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/VariableAnalysis.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/CompiledScriptBlock.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/ScriptBlockToPowerShell.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/MutableTuple.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Binding/Binders.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/ArrayOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/ClassOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/MiscOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/NumericOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/StringOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/runtime/Operations/VariableOps.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/parser/PSType.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/AddInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/ArrayOperations.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/BranchLabel.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/CallInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/CallInstruction.Generated.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/ControlFlowInstructions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/DivInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/DynamicInstructionN.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/DynamicInstructions.Generated.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/DynamicSplatInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/EqualInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/FieldOperations.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/GreaterThanInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/ILightCallSiteBinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/Instruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/InstructionFactory.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/InstructionList.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/InterpretedFrame.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/Interpreter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LabelInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LessThanInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LightCompiler.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LightDelegateCreator.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LightLambda.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LightLambda.Generated.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LightLambdaClosureVisitor.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LocalAccess.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LocalVariables.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/LoopCompiler.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/MulInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/NotEqualInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/NumericConvertInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/PowerShellInstructions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/RuntimeVariables.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/StackOperations.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/SubInstruction.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/TypeOperations.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/interpreter/Utilities.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/AutomationNull.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Pipe.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/pipeline.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/AliasProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/EnvironmentProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/FileSystemContentStream.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/FileSystemProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/FileSystemSecurity.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/FunctionProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/SessionStateProviderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/VariableProvider.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/namespaces/Win32Native.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/Credential.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/MshSecurityException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/nativeMethods.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/Authenticode.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SecurityDescriptorCmdletProviderInterfaces.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateSecurityDescriptorInterface.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SecurityManagerBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/CredentialParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/MshSignature.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/SecuritySupport.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/security/SecurityManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ArgumentTypeConverterAttribute.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/DriveNames.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ProviderNames.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ScopedItemSearcher.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/InitialSessionState.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionState.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateAliasAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateCmdletAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateContainer.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateContent.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateDriveAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateDynamicProperty.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateFunctionAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateItem.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateLocationAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateNavigation.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateProperty.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateProviderAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateScopeAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateVariableAPIs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateCapacityVariable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/QuestionMarkVariable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CultureVariable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateScope.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateScopeEnumerator.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateStrings.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/SessionStateUtils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/ShellVariable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/VariableAttributeCollection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/VariablePath.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/singleshell/config/MshSnapinInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/singleshell/config/RunspaceConfigForSingleShell.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/singleshell/config/MshConsoleInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/singleshell/config/MshConsoleLoadException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/singleshell/config/MshSnapinLoadException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/CoreCLR/CorePsExtensions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/CoreCLR/CorePsStub.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ArchitectureSensitiveAttribute.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/assert.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/CommandDiscoveryExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/CommandProcessorExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/CoreProviderCmdlets.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ExecutionExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ExtensionMethods.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/HostInterfacesExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/IObjectReader.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/IObjectWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MetadataExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshArgumentException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshArgumentNullException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshArgumentOutOfRangeException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshInvalidOperationException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshNotImplementedException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshNotSupportedException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshObjectDisposedException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/MshTraceSource.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ObjectReader.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ObjectStream.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ObjectWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ParameterBinderExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ParserException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/PathUtils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/PsUtils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ResourceManagerCache.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/RuntimeException.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/SessionStateExceptions.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/StringUtil.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/StructuredTraceSource.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/Verbs.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/CryptoUtils.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/PInvokeDllNames.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/PlatformInvokes.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/utils/ClrFacade.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/Utilities/MshObjectUtil.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/Utilities/Mshexpression.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/XmlLoaderBase.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/commands.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionDataMethods.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Complex.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_List.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Misc.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Table.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayDescriptionData_Wide.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/displayResourceManagerCache.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/FormatTable.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataManager.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataQuery.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Complex.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_List.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Table.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Views.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/commands/utility/FormatAndOutput/common/DisplayDatabase/typeDataXmlLoader_Wide.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/PseudoParameterBinder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/CommandCompletion.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/CompletionAnalysis.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/CompletionCompleters.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/CompletionExecutionHelper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/engine/CommandCompletion/CompletionResult.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/MethodInvocationInfo.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/MethodParameter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/MethodParametersCollection.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/QueryBuilder.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/ObjectModelWrapper.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/EnumWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/ScriptWriter.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/cim/WildcardPatternToCimQueryParser.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.objectModel.autogen.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/cmdletization/xml/CoreCLR/cmdlets-over-objects.xmlSerializer.autogen.cs	\
	$(ADMIN_GIT_ROOT)/monad/src/cimSupport/other/ciminstancetypeadapter.cs	\


SYS_AUTO_RES_BASE_PATH=../../../jws/pswin/admin/monad/src/engine/resources

SYS_AUTO_RES_GEN_PATH=gen/SYS_AUTO

SYS_AUTO_RES_GEN_PATH_WIN=gen\SYS_AUTO

SYS_AUTO_RESX_SRCS=\
	../../../jws/pswin/admin/monad/src/engine/resources/Authenticode.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/AutomationExceptions.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CimInstanceTypeAdapterResources.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CmdletizationCoreResources.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CommandBaseStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/Credential.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CredentialAttributeStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ConsoleInfoErrorStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CredUI.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/DescriptionsStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/DiscoveryExceptions.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/EnumExpressionEvaluatorStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ErrorCategoryStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ErrorPackage.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ExtendedTypeSystem.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/EventingResources.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/FileSystemProviderStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/FormatAndOutXmlLoadingStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/GetErrorText.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/HelpDisplayStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/HostInterfaceExceptionsStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/HistoryStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/InternalHostStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/InternalCommandStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/InternalHostUserInterfaceStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/Logging.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/Metadata.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/MshSignature.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ParameterBinderStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ParserStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PathUtilsStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PipelineStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PowerShellStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ProgressRecordStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ProviderBaseSecurity.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/ProxyCommandStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PSCommandStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PSDataBufferStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/PSListModifierStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/RunspaceStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/RunspaceInit.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/RunspacePoolStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/AuthorizationManagerBase.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/SecuritySupportStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/Serialization.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/SessionStateProviderBaseStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/SessionStateStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/SuggestionStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/MiniShellErrors.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/MshHostRawUserInterfaceStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/MshSnapInCmdletResources.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/MshSnapinInfo.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/TypesXmlStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/TransactionStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/WildcardPatternStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/RemotingErrorIdStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/DebuggerStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/FormatAndOut_MshParameter.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/FormatAndOut_format_xxx.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/FormatAndOut_out_xxx.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/NativeCP.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/RegistryProviderStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/TabCompletionStrings.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/CoreClrStubResources.resx	\
	../../../jws/pswin/admin/monad/src/engine/resources/Modules.resx	\


SYS_AUTO_RES_SRCS=\
	gen/SYS_AUTO/Authenticode.resources	\
	gen/SYS_AUTO/AutomationExceptions.resources	\
	gen/SYS_AUTO/CimInstanceTypeAdapterResources.resources	\
	gen/SYS_AUTO/CmdletizationCoreResources.resources	\
	gen/SYS_AUTO/CommandBaseStrings.resources	\
	gen/SYS_AUTO/Credential.resources	\
	gen/SYS_AUTO/CredentialAttributeStrings.resources	\
	gen/SYS_AUTO/ConsoleInfoErrorStrings.resources	\
	gen/SYS_AUTO/CredUI.resources	\
	gen/SYS_AUTO/DescriptionsStrings.resources	\
	gen/SYS_AUTO/DiscoveryExceptions.resources	\
	gen/SYS_AUTO/EnumExpressionEvaluatorStrings.resources	\
	gen/SYS_AUTO/ErrorCategoryStrings.resources	\
	gen/SYS_AUTO/ErrorPackage.resources	\
	gen/SYS_AUTO/ExtendedTypeSystem.resources	\
	gen/SYS_AUTO/EventingResources.resources	\
	gen/SYS_AUTO/FileSystemProviderStrings.resources	\
	gen/SYS_AUTO/FormatAndOutXmlLoadingStrings.resources	\
	gen/SYS_AUTO/GetErrorText.resources	\
	gen/SYS_AUTO/HelpDisplayStrings.resources	\
	gen/SYS_AUTO/HostInterfaceExceptionsStrings.resources	\
	gen/SYS_AUTO/HistoryStrings.resources	\
	gen/SYS_AUTO/InternalHostStrings.resources	\
	gen/SYS_AUTO/InternalCommandStrings.resources	\
	gen/SYS_AUTO/InternalHostUserInterfaceStrings.resources	\
	gen/SYS_AUTO/Logging.resources	\
	gen/SYS_AUTO/Metadata.resources	\
	gen/SYS_AUTO/MshSignature.resources	\
	gen/SYS_AUTO/ParameterBinderStrings.resources	\
	gen/SYS_AUTO/ParserStrings.resources	\
	gen/SYS_AUTO/PathUtilsStrings.resources	\
	gen/SYS_AUTO/PipelineStrings.resources	\
	gen/SYS_AUTO/PowerShellStrings.resources	\
	gen/SYS_AUTO/ProgressRecordStrings.resources	\
	gen/SYS_AUTO/ProviderBaseSecurity.resources	\
	gen/SYS_AUTO/ProxyCommandStrings.resources	\
	gen/SYS_AUTO/PSCommandStrings.resources	\
	gen/SYS_AUTO/PSDataBufferStrings.resources	\
	gen/SYS_AUTO/PSListModifierStrings.resources	\
	gen/SYS_AUTO/RunspaceStrings.resources	\
	gen/SYS_AUTO/RunspaceInit.resources	\
	gen/SYS_AUTO/RunspacePoolStrings.resources	\
	gen/SYS_AUTO/AuthorizationManagerBase.resources	\
	gen/SYS_AUTO/SecuritySupportStrings.resources	\
	gen/SYS_AUTO/Serialization.resources	\
	gen/SYS_AUTO/SessionStateProviderBaseStrings.resources	\
	gen/SYS_AUTO/SessionStateStrings.resources	\
	gen/SYS_AUTO/SuggestionStrings.resources	\
	gen/SYS_AUTO/MiniShellErrors.resources	\
	gen/SYS_AUTO/MshHostRawUserInterfaceStrings.resources	\
	gen/SYS_AUTO/MshSnapInCmdletResources.resources	\
	gen/SYS_AUTO/MshSnapinInfo.resources	\
	gen/SYS_AUTO/TypesXmlStrings.resources	\
	gen/SYS_AUTO/TransactionStrings.resources	\
	gen/SYS_AUTO/WildcardPatternStrings.resources	\
	gen/SYS_AUTO/RemotingErrorIdStrings.resources	\
	gen/SYS_AUTO/DebuggerStrings.resources	\
	gen/SYS_AUTO/FormatAndOut_MshParameter.resources	\
	gen/SYS_AUTO/FormatAndOut_format_xxx.resources	\
	gen/SYS_AUTO/FormatAndOut_out_xxx.resources	\
	gen/SYS_AUTO/NativeCP.resources	\
	gen/SYS_AUTO/RegistryProviderStrings.resources	\
	gen/SYS_AUTO/TabCompletionStrings.resources	\
	gen/SYS_AUTO/CoreClrStubResources.resources	\
	gen/SYS_AUTO/Modules.resources	\


SYS_AUTO_RES_CS_SRCS=\
	gen/SYS_AUTO/Authenticode.cs	\
	gen/SYS_AUTO/AutomationExceptions.cs	\
	gen/SYS_AUTO/CimInstanceTypeAdapterResources.cs	\
	gen/SYS_AUTO/CmdletizationCoreResources.cs	\
	gen/SYS_AUTO/CommandBaseStrings.cs	\
	gen/SYS_AUTO/Credential.cs	\
	gen/SYS_AUTO/CredentialAttributeStrings.cs	\
	gen/SYS_AUTO/ConsoleInfoErrorStrings.cs	\
	gen/SYS_AUTO/CredUI.cs	\
	gen/SYS_AUTO/DescriptionsStrings.cs	\
	gen/SYS_AUTO/DiscoveryExceptions.cs	\
	gen/SYS_AUTO/EnumExpressionEvaluatorStrings.cs	\
	gen/SYS_AUTO/ErrorCategoryStrings.cs	\
	gen/SYS_AUTO/ErrorPackage.cs	\
	gen/SYS_AUTO/ExtendedTypeSystem.cs	\
	gen/SYS_AUTO/EventingResources.cs	\
	gen/SYS_AUTO/FileSystemProviderStrings.cs	\
	gen/SYS_AUTO/FormatAndOutXmlLoadingStrings.cs	\
	gen/SYS_AUTO/GetErrorText.cs	\
	gen/SYS_AUTO/HelpDisplayStrings.cs	\
	gen/SYS_AUTO/HostInterfaceExceptionsStrings.cs	\
	gen/SYS_AUTO/HistoryStrings.cs	\
	gen/SYS_AUTO/InternalHostStrings.cs	\
	gen/SYS_AUTO/InternalCommandStrings.cs	\
	gen/SYS_AUTO/InternalHostUserInterfaceStrings.cs	\
	gen/SYS_AUTO/Logging.cs	\
	gen/SYS_AUTO/Metadata.cs	\
	gen/SYS_AUTO/MshSignature.cs	\
	gen/SYS_AUTO/ParameterBinderStrings.cs	\
	gen/SYS_AUTO/ParserStrings.cs	\
	gen/SYS_AUTO/PathUtilsStrings.cs	\
	gen/SYS_AUTO/PipelineStrings.cs	\
	gen/SYS_AUTO/PowerShellStrings.cs	\
	gen/SYS_AUTO/ProgressRecordStrings.cs	\
	gen/SYS_AUTO/ProviderBaseSecurity.cs	\
	gen/SYS_AUTO/ProxyCommandStrings.cs	\
	gen/SYS_AUTO/PSCommandStrings.cs	\
	gen/SYS_AUTO/PSDataBufferStrings.cs	\
	gen/SYS_AUTO/PSListModifierStrings.cs	\
	gen/SYS_AUTO/RunspaceStrings.cs	\
	gen/SYS_AUTO/RunspaceInit.cs	\
	gen/SYS_AUTO/RunspacePoolStrings.cs	\
	gen/SYS_AUTO/AuthorizationManagerBase.cs	\
	gen/SYS_AUTO/SecuritySupportStrings.cs	\
	gen/SYS_AUTO/Serialization.cs	\
	gen/SYS_AUTO/SessionStateProviderBaseStrings.cs	\
	gen/SYS_AUTO/SessionStateStrings.cs	\
	gen/SYS_AUTO/SuggestionStrings.cs	\
	gen/SYS_AUTO/MiniShellErrors.cs	\
	gen/SYS_AUTO/MshHostRawUserInterfaceStrings.cs	\
	gen/SYS_AUTO/MshSnapInCmdletResources.cs	\
	gen/SYS_AUTO/MshSnapinInfo.cs	\
	gen/SYS_AUTO/TypesXmlStrings.cs	\
	gen/SYS_AUTO/TransactionStrings.cs	\
	gen/SYS_AUTO/WildcardPatternStrings.cs	\
	gen/SYS_AUTO/RemotingErrorIdStrings.cs	\
	gen/SYS_AUTO/DebuggerStrings.cs	\
	gen/SYS_AUTO/FormatAndOut_MshParameter.cs	\
	gen/SYS_AUTO/FormatAndOut_format_xxx.cs	\
	gen/SYS_AUTO/FormatAndOut_out_xxx.cs	\
	gen/SYS_AUTO/NativeCP.cs	\
	gen/SYS_AUTO/RegistryProviderStrings.cs	\
	gen/SYS_AUTO/TabCompletionStrings.cs	\
	gen/SYS_AUTO/CoreClrStubResources.cs	\
	gen/SYS_AUTO/Modules.cs	\


SYS_AUTO_RES_REF=\
	-resource:gen/SYS_AUTO/Authenticode.resources	\
	-resource:gen/SYS_AUTO/AutomationExceptions.resources	\
	-resource:gen/SYS_AUTO/CimInstanceTypeAdapterResources.resources	\
	-resource:gen/SYS_AUTO/CmdletizationCoreResources.resources	\
	-resource:gen/SYS_AUTO/CommandBaseStrings.resources	\
	-resource:gen/SYS_AUTO/Credential.resources	\
	-resource:gen/SYS_AUTO/CredentialAttributeStrings.resources	\
	-resource:gen/SYS_AUTO/ConsoleInfoErrorStrings.resources	\
	-resource:gen/SYS_AUTO/CredUI.resources	\
	-resource:gen/SYS_AUTO/DescriptionsStrings.resources	\
	-resource:gen/SYS_AUTO/DiscoveryExceptions.resources	\
	-resource:gen/SYS_AUTO/EnumExpressionEvaluatorStrings.resources	\
	-resource:gen/SYS_AUTO/ErrorCategoryStrings.resources	\
	-resource:gen/SYS_AUTO/ErrorPackage.resources	\
	-resource:gen/SYS_AUTO/ExtendedTypeSystem.resources	\
	-resource:gen/SYS_AUTO/EventingResources.resources	\
	-resource:gen/SYS_AUTO/FileSystemProviderStrings.resources	\
	-resource:gen/SYS_AUTO/FormatAndOutXmlLoadingStrings.resources	\
	-resource:gen/SYS_AUTO/GetErrorText.resources	\
	-resource:gen/SYS_AUTO/HelpDisplayStrings.resources	\
	-resource:gen/SYS_AUTO/HostInterfaceExceptionsStrings.resources	\
	-resource:gen/SYS_AUTO/HistoryStrings.resources	\
	-resource:gen/SYS_AUTO/InternalHostStrings.resources	\
	-resource:gen/SYS_AUTO/InternalCommandStrings.resources	\
	-resource:gen/SYS_AUTO/InternalHostUserInterfaceStrings.resources	\
	-resource:gen/SYS_AUTO/Logging.resources	\
	-resource:gen/SYS_AUTO/Metadata.resources	\
	-resource:gen/SYS_AUTO/MshSignature.resources	\
	-resource:gen/SYS_AUTO/ParameterBinderStrings.resources	\
	-resource:gen/SYS_AUTO/ParserStrings.resources	\
	-resource:gen/SYS_AUTO/PathUtilsStrings.resources	\
	-resource:gen/SYS_AUTO/PipelineStrings.resources	\
	-resource:gen/SYS_AUTO/PowerShellStrings.resources	\
	-resource:gen/SYS_AUTO/ProgressRecordStrings.resources	\
	-resource:gen/SYS_AUTO/ProviderBaseSecurity.resources	\
	-resource:gen/SYS_AUTO/ProxyCommandStrings.resources	\
	-resource:gen/SYS_AUTO/PSCommandStrings.resources	\
	-resource:gen/SYS_AUTO/PSDataBufferStrings.resources	\
	-resource:gen/SYS_AUTO/PSListModifierStrings.resources	\
	-resource:gen/SYS_AUTO/RunspaceStrings.resources	\
	-resource:gen/SYS_AUTO/RunspaceInit.resources	\
	-resource:gen/SYS_AUTO/RunspacePoolStrings.resources	\
	-resource:gen/SYS_AUTO/AuthorizationManagerBase.resources	\
	-resource:gen/SYS_AUTO/SecuritySupportStrings.resources	\
	-resource:gen/SYS_AUTO/Serialization.resources	\
	-resource:gen/SYS_AUTO/SessionStateProviderBaseStrings.resources	\
	-resource:gen/SYS_AUTO/SessionStateStrings.resources	\
	-resource:gen/SYS_AUTO/SuggestionStrings.resources	\
	-resource:gen/SYS_AUTO/MiniShellErrors.resources	\
	-resource:gen/SYS_AUTO/MshHostRawUserInterfaceStrings.resources	\
	-resource:gen/SYS_AUTO/MshSnapInCmdletResources.resources	\
	-resource:gen/SYS_AUTO/MshSnapinInfo.resources	\
	-resource:gen/SYS_AUTO/TypesXmlStrings.resources	\
	-resource:gen/SYS_AUTO/TransactionStrings.resources	\
	-resource:gen/SYS_AUTO/WildcardPatternStrings.resources	\
	-resource:gen/SYS_AUTO/RemotingErrorIdStrings.resources	\
	-resource:gen/SYS_AUTO/DebuggerStrings.resources	\
	-resource:gen/SYS_AUTO/FormatAndOut_MshParameter.resources	\
	-resource:gen/SYS_AUTO/FormatAndOut_format_xxx.resources	\
	-resource:gen/SYS_AUTO/FormatAndOut_out_xxx.resources	\
	-resource:gen/SYS_AUTO/NativeCP.resources	\
	-resource:gen/SYS_AUTO/RegistryProviderStrings.resources	\
	-resource:gen/SYS_AUTO/TabCompletionStrings.resources	\
	-resource:gen/SYS_AUTO/CoreClrStubResources.resources	\
	-resource:gen/SYS_AUTO/Modules.resources	\


SYS_AUTO_make_rule_RES_SRCS: $(SYS_AUTO_RES_SRCS)

SYS_AUTO_make_rule_RES_CS_SRCS: $(SYS_AUTO_RES_CS_SRCS)

SYS_AUTO_TARGET=System.Management.Automation

