BASE_PATH = ../src/monad/wmi/WMIv2/Client/DotNetAPI/cs

WMI_SRCS = \
	${BASE_PATH}/CancellationMode.cs \
	${BASE_PATH}/CimApplication.cs \
	${BASE_PATH}/CimAsyncCallbacksReceiverBase.cs \
	${BASE_PATH}/CimAsyncCancellationDisposable.cs \
	${BASE_PATH}/CimAsyncCollection.cs \
	${BASE_PATH}/CimAsyncClassObservable.cs \
	${BASE_PATH}/CimAsyncClassObserverProxy.cs \
	${BASE_PATH}/CimAsyncDelegatedObservable.cs \
	${BASE_PATH}/CimAsyncInstanceObservable.cs \
	${BASE_PATH}/CimAsyncInstanceObserverProxy.cs \
	${BASE_PATH}/CimAsyncIndicationObservable.cs \
	${BASE_PATH}/CimAsyncIndicationObserverProxy.cs \
	${BASE_PATH}/CimAsyncMethodResultObservable.cs \
	${BASE_PATH}/CimAsyncMethodResultObserverProxy.cs \
	${BASE_PATH}/CimAsyncObservableBase.cs \
	${BASE_PATH}/CimAsyncObserverProxyBase.cs \
	${BASE_PATH}/CimAsyncResult.cs \
	${BASE_PATH}/CimAsyncStatus.cs \
	${BASE_PATH}/CimClass.cs \
	${BASE_PATH}/CimCredential.cs \
	${BASE_PATH}/CimClassPropertiesCollection.cs \
	${BASE_PATH}/CimClassPropertyOfClass.cs \
	${BASE_PATH}/CimConverter.cs \
	${BASE_PATH}/CimDeserializer.cs \
	${BASE_PATH}/CimException.cs \
	${BASE_PATH}/CimFlags.cs \
	${BASE_PATH}/CimInstance.cs \
	${BASE_PATH}/CimKeyedCollection.cs \
	${BASE_PATH}/CimPropertyDeclaration.cs \
	${BASE_PATH}/CimMethodDeclaration.cs \
	${BASE_PATH}/CimMethodDeclarationCollection.cs \
	${BASE_PATH}/CimMethodDeclarationOfClass.cs \
	${BASE_PATH}/CimMethodQualifierCollection.cs \
	${BASE_PATH}/CimMethodQualifierOfMethod.cs \
	${BASE_PATH}/CimMethodParameterDeclaration.cs \
	${BASE_PATH}/CimMethodParameterDeclarationCollection.cs \
	${BASE_PATH}/CimMethodParameterDeclarationOfMethod.cs \
	${BASE_PATH}/CimMethodParameterQualifierOfMethod.cs \
	${BASE_PATH}/CimMethodParameterQualifierCollection.cs \
	${BASE_PATH}/CimMethodParameter.cs \
	${BASE_PATH}/CimMethodParameterBackedByCimProperty.cs \
	${BASE_PATH}/CimMethodParametersCollection.cs \
	${BASE_PATH}/CimMethodResultBase.cs \
	${BASE_PATH}/CimMethodResult.cs \
	${BASE_PATH}/CimMethodStreamedResult.cs \
	${BASE_PATH}/CimOperation.cs \
	${BASE_PATH}/CimOperationFlags.cs \
	${BASE_PATH}/CimOperationOptions.cs \
	${BASE_PATH}/CimProperty.cs \
	${BASE_PATH}/CimPropertyStandalone.cs \
	${BASE_PATH}/CimPropertyOfInstance.cs \
	${BASE_PATH}/CimPropertiesCollection.cs \
	${BASE_PATH}/CimPropertyQualifierCollection.cs \
	${BASE_PATH}/CimQualifier.cs \
	${BASE_PATH}/CimClassQualifierCollection.cs \
	${BASE_PATH}/CimQualifierOfClass.cs \
	${BASE_PATH}/CimQualifierOfProperty.cs \
	${BASE_PATH}/CimReadOnlyKeyedCollection.cs \
	${BASE_PATH}/CimSemantics.cs \
	${BASE_PATH}/CimSystemProperties.cs \
	${BASE_PATH}/CimSerializer.cs \
	${BASE_PATH}/CimSession.cs \
	${BASE_PATH}/CimSessionOptions.cs \
	${BASE_PATH}/CimSyncClassEnumerable.cs \
	${BASE_PATH}/CimSyncClassEnumerator.cs \
	${BASE_PATH}/CimSyncEnumerableBase.cs \
	${BASE_PATH}/CimSyncEnumeratorBase.cs \
	${BASE_PATH}/CimSyncIndicationEnumerable.cs \
	${BASE_PATH}/CimSyncIndicationEnumerator.cs \
	${BASE_PATH}/CimSyncInstanceEnumerable.cs \
	${BASE_PATH}/CimSyncInstanceEnumerator.cs \
	${BASE_PATH}/CimSubscriptionDeliveryOptions.cs \
	${BASE_PATH}/CimSubscriptionResult.cs \
	${BASE_PATH}/CimType.cs \
	${BASE_PATH}/ConvertingObservable.cs \
	${BASE_PATH}/DComSessionOptions.cs \
	${BASE_PATH}/EmptyDisposable.cs \
	${BASE_PATH}/Helpers.cs \
	${BASE_PATH}/ImpersonationType.cs \
	${BASE_PATH}/NativeErrorCode.cs \
	${BASE_PATH}/PacketEncoding.cs \
	${BASE_PATH}/ProxyType.cs \
	${BASE_PATH}/SharedInstanceHandle.cs \
	${BASE_PATH}/WSManSessionOptions.cs \
	${BASE_PATH}/Strings.Designer.cs

REMOVED=string_resources/AssemblyInfo.cs 
