name: 'PR Backporter'
description: 'Backports a pull request to a branch using the "/backport to <branch>" comment'
inputs:
  target_branch:
    description: 'Backport target branch.'
  auth_token:
    description: 'The token used to authenticate to GitHub.'
  pr_title_template:
      description: 'The template used for the PR title. Special placeholder tokens that will be replaced with a value: %target_branch%, %source_pr_title%, %source_pr_number%, %cc_users%.'
      default: '[%target_branch%] %source_pr_title%'
  pr_description_template:
    description: 'The template used for the PR description. Special placeholder tokens that will be replaced with a value: %target_branch%, %source_pr_title%, %source_pr_number%, %cc_users%.'
    default: |
      Backport of #%source_pr_number% to %target_branch%

      /cc %cc_users%

runs:
  using: 'node12'
  main: 'index.js'
