[ClassVersion("1.0.0"), Description("The configuration provider for files and directories."), FriendlyName("nxFile")]
class MSFT_nxFileResource:OMI_BaseResource
{
	[Key] string DestinationPath; 
	[Write] string SourcePath;
	[Write,ValueMap{"present", "absent"},Values{"present", "absent"}] string Ensure;
	[Write,ValueMap{"file", "directory", "link"},Values{"file", "directory","link"}] string Type;
	[Write] boolean Force;
	[Write] string Contents;
	[Write, ValueMap{"md5", "mtime", "ctime"}] string Checksum;
	[Write] boolean Recurse;
	[Write, ValueMap{"follow", "manage", "ignore" }] string Links;
	[Write] string Group;
	[Write] string Mode;
	[Write] string Owner;
	[Read] datetime ModifiedDate; 
};
