[ClassVersion("1.0.0"), FriendlyName("nxPackage")] 
class MSFT_nxPackageResource : OMI_BaseResource
{
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Yum", "Apt", "Zypper", "*"},Values{"Yum", "Apt", "Zypper", "*"}] string PackageManager;
  [Key] string Name;
  [write] string FilePath;
  [write] Boolean PackageGroup;
  [write] string Arguments;
  [write] uint32 ReturnCode;
  [read] string PackageDescription;
  [read] string Publisher;
  [read] string InstalledOn;
  [read] uint32 Size;
  [read] string Version;
  [read] boolean Installed;
  [read] string Architecture;
  
};
