name: powershell/PowerShell-CI-linux
on:
  workflow_dispatch:
    inputs:
      ContainerPattern:
        description: |
          Pattern to match JobName of the container.
          Update this to force a container.
          `.` will match everything
        default: "."
        type: string
        required: false
  push:
    branches:
    - master
    - release*
    - feature*
    paths:
    - "*"
    - "!.vsts-ci/misc-analysis.yml"
    - "!.github/ISSUE_TEMPLATE/*"
    - "!.github/workflows/*"
    - "!.dependabot/config.yml"
    - "!.pipelines/*"
    - "!test/perf/*"
  pull_request:
    branches:
    - master
    - release*
    - feature*
    paths:
    - "*"
    - "!.dependabot/config.yml"
    - "!.github/ISSUE_TEMPLATE/*"
    - "!.github/workflows/*"
    - "!.vsts-ci/misc-analysis.yml"
    - "!.vsts-ci/windows.yml"
    - "!.vsts-ci/windows/*"
    - "!tools/cgmanifest.json"
    - "!LICENSE.txt"
    - "!test/common/markdown/*"
    - "!test/perf/*"
    - "!tools/releaseBuild/*"
    - "!tools/install*"
    - "!tools/releaseBuild/azureDevOps/templates/*"
    - "!README.md"
    - "!.spelling"
    - "!.pipelines/*"
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  FORCE_FEATURE: 'False'
  FORCE_PACKAGE: 'False'
  NUGET_KEY: none
  POWERSHELL_TELEMETRY_OPTOUT: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
  system_debug: 'false'
jobs:
  vsts_ci_templates_ci_build:
    name: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_ci_build.yml"
    with:
      pool: ubuntu-20.04
      jobName: linux_build
      displayName: linux Build
  vsts_ci_templates_nix_test:
    name: vsts_ci_templates_nix_test
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: CI
      name: Ubuntu
  vsts_ci_templates_nix_test_2:
    name: vsts_ci_templates_nix_test_2
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: CI
      name: Ubuntu
  vsts_ci_templates_nix_test_3:
    name: vsts_ci_templates_nix_test_3
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: Others
      name: Ubuntu
  vsts_ci_templates_nix_test_4:
    name: vsts_ci_templates_nix_test_4
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: Others
      name: Ubuntu
  vsts_ci_templates_verify_xunit:
    name: vsts_ci_templates_verify_xunit
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_verify_xunit.yml"
    with:
      pool: ubuntu-20.04
  TestContainer-getContainerJob:
    name: Choose a container
    needs:
    - vsts_ci_templates_ci_build
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/checkout@v4.1.0
    - uses: actions/checkout@v4.1.0
      with:
        repository: PowerShell/PowerShell-Docker
        ref: master
        token: "${{ secrets.CHECKOUT_TOKEN }}"
    - name: Initialize Container Stage
      id: getContainerTask
      continue-on-error: true
      run: |-
        # Initialize container test stage
        Import-Module ./PowerShell/tools/ci.psm1
        Invoke-InitializeContainerStage -ContainerPattern '${{ parameters.ContainerPattern }}'
      shell: pwsh
  vsts_ci_templates_test_nix_container_test:
    name: vsts_ci_templates_test_nix_container_test
    needs:
    - TestContainer-getContainerJob
    - vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_test_nix_container_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: CI
      name: container
  vsts_ci_templates_test_nix_container_test_2:
    name: vsts_ci_templates_test_nix_container_test_2
    needs:
    - TestContainer-getContainerJob
    - vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_test_nix_container_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: CI
      name: container
  vsts_ci_templates_test_nix_container_test_3:
    name: vsts_ci_templates_test_nix_container_test_3
    needs:
    - TestContainer-getContainerJob
    - vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_test_nix_container_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: UnelevatedPesterTests
      tagSet: Others
      name: container
  vsts_ci_templates_test_nix_container_test_4:
    name: vsts_ci_templates_test_nix_container_test_4
    needs:
    - TestContainer-getContainerJob
    - vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_test_nix_container_test.yml"
    with:
      pool: ubuntu-20.04
      purpose: ElevatedPesterTests
      tagSet: Others
      name: container
  vsts_ci_linux_templates_packaging:
    name: vsts_ci_linux_templates_packaging
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_linux_templates_packaging.yml"
    with:
      pool: ubuntu-20.04
